- src/Swashbuckle/Application/SwaggerServiceCollectionExtensions.cs
Just in case someone has modified serialization settings, like using camecase, then the swagger generator should pick them up
> use serialization options present in the pipeline

- src/Swashbuckle/Swagger/SwaggerDocumentOptions.cs
- src/Swashbuckle/Swagger/SwaggerSchemaOptions.cs
The OperationFilter, ModelFilter and DocumentFilter methods in the options classes with a IxxxFilter instance as paramater don't need to have a "where : new()." With the "new()", it's impossible to set a ApplyXmlActionComments or ApplyXmlTypeComments filter because these filters don't have a paramtereless constructor.
> Remove new() on OperationFilter, ModelFilter and DocumentFilter methods

- src/Swashbuckle.SwaggerGen/Application/SwaggerGenBuilderExtensions.cs
- src/Swashbuckle.SwaggerUi/Application/SwaggerUiBuilderExtensions.cs
By convention, extensions to `IAppBuilder` should return the builder so additional middleware can be chained in.
> AppBuilder extensions should return the builder for chaining.

- src/Swashbuckle.SwaggerGen/Generator/SwaggerDocument.cs
Changes `Response.Headers` collection type to `IDictionary<string, Header>`. This fixes the output `SwaggerDocument` to match the Swagger schema.
> Fix Response Headers collection type to match Swagger spec

- src/Swashbuckle.Swagger/Application/SwaggerSerializerFactory.cs
Enables user control over swagger.json document formatting. MvcJsonOptions preference is used when serializing swagger.json.
> Use MvcJsonOptions serializer formatting for swagger.json

- src/Swashbuckle.SwaggerUi/project.json
I'd like to use the SwaggerUi library outside of ASP.NET Core MVC. The library currently has a dependency on AspNetCore.Mvc.Core even though it doesn't need it.
This PR would remove this dependency and add back only the required dependencies.
> Remove dependency on MVC in SwaggerUi

- src/Swashbuckle.SwaggerGen/Generator/SchemaExtensions.cs
- test/Swashbuckle.SwaggerGen.Test/Generator/SchemaRegistryTests.cs
- test/Swashbuckle.SwaggerGen.Test/TestFixtures/Types/DataAnnotatedType.cs
I had the need to populate with some some interesting data in all the properties of my Models, thought it would be useful for others as well
> Added support for DefaultValue data annontation attribute

- src/Swashbuckle.AspNetCore.SwaggerGen/Annotations/SwaggerSchemaFilterAttribute.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Annotations/SwaggerAttributesSchemaFilterTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/TestFixtures/Types/SwaggerAnnotatedType.cs
Added `Struct` to `AttributeTargets` of `SwaggerSchemaFilterAttribute` so that you can document value types.
* Minor changes to `SwaggerSchemaFilterAttribute` and `SwaggerAttributesSchemaFilterTests`
> SwaggerSchemaFilterAttribute on structs

- src/Swashbuckle.AspNetCore.SwaggerGen/Annotations/XmlCommentsOperationFilter.cs
> Fixing exception caused by null ModelMetadata in XmlCommentsOperationFilter.cs

- README.md
The `SecurityRequirementsOperationFilter` is incorrectly mapping a policy name to claim types, there is a comment about this but it would be much better to map to the actual claim types which we can get quite easily from the AuthorizationOptions which is populated with policies like so:
```
services.AddAuthorization(
options =>
{
options.AddPolicy("ReadPolicy", x => x.RequireClaim("read-customer"));
});
```
> Fix SecurityRequirementsOperationFilter

- README.md
Addresses part of #341 by making it much clearer that conventionally-routed controllers won't get represented.
> Update README to warn against conventional routing

- src/Swashbuckle.AspNetCore.Swagger/Model/SwaggerDocument.cs
Adding the possibility to reference global parameters is the only thing that was missing to better integrate with AutoRest and AspNet Versioning. 
Api Version parameter should be global and referenced by actions so that AutoRest generates a client with implicit version instead of a parameter for each method.
> Add $ref field to NonBodyParameter

- .gitattributes
- README.md
- src/Swashbuckle.AspNetCore.SwaggerUI/Application/SwaggerUIOptions.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/Template/IndexSettings.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/Template/index.html
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerUIIntegrationTests.cs
- test/WebSites/CustomUIConfig/Startup.cs
By default, the Swagger UI will have a generic document title (e.g. 'Swagger UI'). When you have multiple Swagger pages open, it can be difficult to tell them apart.
> Allow the SwaggerUI Document title to be configurable

- src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SchemaRegistry.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Generator/SchemaRegistryTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/TestFixtures/Types/ExtensionDataObjectType.cs
Added support for building AdditionalProperties in Schema off of JsonExtensionDataAttributes.
See: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/389
> JsonExtensionDataAttribute Support

- src/Swashbuckle.AspNetCore.Swagger/Application/SwaggerMiddleware.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerGenIntegrationTests.cs
Removes the BOM from the response as a BOM is not required and not recommended for UTF-8 (https://stackoverflow.com/a/2223926/5173536)
@domaindrivendev I've modified the integrationTests to check for the absence of a BOM and all are passing locally. Let me know if you want me to change some things.
Fixes #574
> Removed ByteOrderMark from .json response

- src/Swashbuckle.AspNetCore.SwaggerUI/Application/SwaggerUIBuilderExtensions.cs
UseSwaggerUI will check for special case empty RoutePrefix and allow mapping swagger UI to application root url.
> Support to map swagger UI to application root url

- src/Swashbuckle.AspNetCore.SwaggerGen/Generator/ApiDescriptionExtensions.cs
> Allow ApiDescriptionExtensions.ControllerAttributes() and .ActionAttributes() to return inherited attributes.

- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIIndexMiddleware.cs
PR for https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/600
Based on response from https://github.com/aspnet/BasicMiddleware/issues/307#issuecomment-369974928
here's a async-await fixup to for ResponseCompression usage when full .net framework is used
> Proper async-await usage for response Stream in SwaggerUI middleware

- src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SchemaExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SchemaRegistry.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Generator/SchemaRegistryTests.cs
- test/WebSites/Basic/Controllers/EnumParamsController.cs
- test/WebSites/Basic/Startup.cs
This basically changes the behavior of `DescribeAllEnumsAsStrings` for Enum types to generate a `Ref` for the parameter rather than generate the supported values inline.
Addresses #358
> Generate schema / references for enum action parameters #358

- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIIndexMiddleware.cs
If the application has default `JsonConvert` options configured as following, the Swagger-UI completely fails to load:
```csharp
JsonConvert.DefaultSettings = () => new JsonSerializerSettings
{
Formatting = Formatting.Indented
};
```
This happens because the generated configuration object looks like this:
```javascript
window.onload = function () {
var configObject = JSON.parse('{
"urls": [
{
"url": "/swagger/v1/swagger.json",
"name": "v1"
}
],
"validatorUrl": null
}');
```
That is, the generated configuration contains new lines, which breaks the JavaScript with `SyntaxError: unterminated string literal` error.
Passing `Formatting.None` to `JsonConvert.SerializeObject` should ensure Swagger-UI does not depend on the external configuration and in turn does not break if the `Indented` …
> Force JsonConvert not to use formatting

- src/Swashbuckle.AspNetCore.SwaggerGen/Application/SwaggerGenServiceCollectionExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/Application/SwaggerUIBuilderExtensions.cs
Configuration may be fetched via other sources like this:
```
services.AddSingleton<IConfigureOptions<SwaggerGenOptions>, MySwaggerOptionsConfigurator>();
services.AddSingleton<IConfigureOptions<SwaggerUIOptions>, MySwaggerOptionsConfigurator>();
```
Then the Action is really "dont-care". As it is now, I have to provide an empty lambda :/
> Makes configure actions optional.

- README.md
The ProducesResponseTypeAttribute now has a [default constructor](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ProducesResponseTypeAttribute.cs#L20), so there is no need to pass typeof(void) along
> Docs Update: Remove typeof(void) from ProducesResponseType

- src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SchemaRegistry.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Generator/SchemaRegistryTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Swashbuckle.AspNetCore.SwaggerGen.Test.csproj
This should solve issue #471.
I tried to withhold from adding FSharp.Core reference to the project, but it seems useful to me to have it in the test library.
I'm not sure about the version bump to Microsoft.NETCore.Platforms: it helped me to build locally. Otherwise, I got "Detected package downgrade: Microsoft.NETCore.Platforms from 1.1.0 to 1.0.2." error.
> Fsharp option type support

- src/Swashbuckle.AspNetCore.Swagger/Application/SwaggerMiddleware.cs
Fix #384 
It provides an ability to correctly display commentaries in foreign languages (Russian, for instance) in swagger.json
> set charset=utf-8 for swagger.json content-type

- src/Swashbuckle.AspNetCore.SwaggerUI/Swashbuckle.AspNetCore.SwaggerUI.csproj
Chrome dev tools send requests for the `.map` files for the bundled css and js files from swagger-ui-dist. If those are included via swashbuckle, it would prevent the 404s on the server hosting the Swagger UI.
> Include .map files from swagger-ui-dist to prevent 404s

- src/Swashbuckle.AspNetCore.ReDoc/Swashbuckle.AspNetCore.ReDoc.csproj
- src/Swashbuckle.AspNetCore.Swagger/Swashbuckle.AspNetCore.Swagger.csproj
- src/Swashbuckle.AspNetCore.SwaggerGen/Swashbuckle.AspNetCore.SwaggerGen.csproj
- src/Swashbuckle.AspNetCore.SwaggerUI/Swashbuckle.AspNetCore.SwaggerUI.csproj
- src/Swashbuckle.AspNetCore/Swashbuckle.AspNetCore.csproj
Nuget provides elements to specify where the source code repository is for a nuget package, by specifying a [repository element](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/compiler/resources/nuspec.xsd#L67).
It would be great if we had this information straight into the .nuspec, which would allow tooling such as [Renovate](https://renovatebot.com/) to fetch detailed information about releases (what specifically has been fixed [sample](https://github.com/tomkerkhove/promitor/pull/101)).
This adds the repository location to the nuspec.
Kudos to @samneirinck to provide .NET support to Renovate.
> Add Repository information to packaging information

- README.md
Hello
I am the maintainer of Swashbuckle.Examples and Swashbuckle.AspNetCore.Filters (was Swashbuckle.AspNetCore.Examples), two small packages which contain a few Swashbuckle OperationFilters I have written and find useful, and apparently others find useful too as they get around 300 downloads per day.
Is it cheeky of me to add a link to my package in your readme?
> Add link to Swashbuckle.AspNetCore.Filters in ReadMe

- src/Swashbuckle.AspNetCore.Swagger/Model/SwaggerDocument.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/Generator/ApiParameterDescriptionExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SchemaExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Generator/SwaggerGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/TestFixtures/Fakes/FakeApiDescriptionGroupCollectionProvider.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/TestFixtures/Fakes/FakeController.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/TestFixtures/Types/BindingAnnotatedType.cs
- test/WebSites/Basic/Controllers/FileUploadsController.cs
Addresses #193 by generating a correct description (e.g. in=formData, type=file) for parameters of type `IFormFile`
> Support form file parameters

- README.md
- src/Swashbuckle.AspNetCore.SwaggerGen/Application/ConfigureSwaggerGeneratorOptions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/Application/SwaggerGenOptionsExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/Generator/ApiDescriptionExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SwaggerGenerator.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SwaggerGeneratorOptions.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Generator/SwaggerGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/TestFixtures/Fakes/FakeApiDescriptionGroupCollectionProvider.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/TestFixtures/Fakes/FakeController.cs
- test/WebSites/Basic/Controllers/CrudActionsController.cs
- test/WebSites/Basic/Controllers/DataAnnotationsController.cs
- test/WebSites/Basic/Controllers/ResponseTypeAnnotationsController.cs
- test/WebSites/Basic/Controllers/SwaggerAnnotationsController.cs
- test/WebSites/Basic/Startup.cs
- test/WebSites/CliExample/Controllers/ProductsController.cs
- test/WebSites/ConfigFromFile/Controllers/ProductsController.cs
- test/WebSites/CustomUIConfig/Controllers/ProductsController.cs
- test/WebSites/CustomUIIndex/Controllers/ProductsController.cs
- test/WebSites/MultipleVersions/V1/ProductsController.cs
- test/WebSites/MultipleVersions/V2/ProductsController.cs
- test/WebSites/OAuth2Integration/ResourceServer/Controllers/ProductsController.cs
- test/WebSites/ReDoc/Controllers/ProductsController.cs
Addresses #333.
In summary, this removes the code that automatically creates an `OperationId` from route and parameter info, and reverts to explicit assignment, using route name if provided (e.g. `[HttpGet("products", Name = "GetProducts")]`) or else the action name.
Trying to maintain a systematic way to generate a meaningful `OperationId` that works for everyone has proved to be extremely difficult, if not impossible. Given that the `OperationId` is used by many code-gen tools in the generation of client libraries, I believe the explicit approach makes most sense.
With that said, this puts the onus on developers to come up with meaningful and unique names.
> Use action name or route name for OperationIds

- src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SwaggerGenerator.cs
Improves reliability of the function in case the user passes a lowercase `httpMethod`.
> Make httpMethod not case-sensitive

- README.md
The default instructions leave the user wondering where Info lives - the project won't compile without a Google.
> Add Using info to README

- src/Swashbuckle.AspNetCore.Annotations/AnnotationsOperationFilter.cs
The swaggerResponseAttribute does not register the `Type`, this PR fixes that bug.
> Add schema to response

- src/Swashbuckle.AspNetCore.Swagger/Model/ISwaggerProvider.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SwaggerGenerator.cs
- version.props
When an UnknownSwaggerDocument is passed include the known documents in
the error message so that the user can identify examples of valid
options.
For example in my case this helped me know that a semi-colon got into my command some how:
> Improve UnknownSwaggerDocument error message

- src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SwaggerGenerator.cs
Fixes #942
The consumes array was producing duplicate entries. This fix returns only distinct entries.
> fixes #942 duplicate consume entries

- src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SchemaRegistry.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Generator/SchemaRegistryTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Generator/SwaggerGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/TestFixtures/Types/ComplexType.cs
Fix, with tests, for #1027.
Note that the API test for `ComplexType` is now returning six properties (i.e. ignoring the new write-only property) automatically; it was only Swashbuckle that needed to be changed to also ignore it.
I hope I've put the check for non-readable properties in a sensible place, but let me know if not!
> Fix Swashbuckle not tagging write-only properties

- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs
Adding the charset to the ContentType, when delivering the html.
Since the response is encoded in utf-8 (see line 93) it makes sense to also include that in the ContentType.
Not sure what happened to that bracket at the end of the file.
> Updating content-type header for swagger page

- src/Swashbuckle.AspNetCore.Cli/Program.cs
If `dotnet-swagger.dll` is placed in a path with spaces then the assembly location used when respawning `dotnet` is not escaped.
Fixes #845
> Escape `dotnet-swagger.dll` path in CLI tool

- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsSchemaFilter.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsSchemaFilterTests.cs
This code:
```
var jsonProperty = jsonObjectContract.Properties[entry.Key];
if (jsonProperty == null) continue;
```
will fail with at the first line with an exception when entry.Key is not present in the dictionary. The check should be done beforehand. I added a rudimentary test that fails without this change, but passes after the change is introduced. Thanks.
> [Bugfix] Ignore missing properties when mapping metadata

- README-v5.md
- src/Swashbuckle.AspNetCore.ReDoc/ReDocBuilderExtensions.cs
- src/Swashbuckle.AspNetCore.ReDoc/ReDocMiddleware.cs
- src/Swashbuckle.AspNetCore.ReDoc/ReDocOptions.cs
- src/Swashbuckle.AspNetCore.ReDoc/ReDocOptionsExtensions.cs
- src/Swashbuckle.AspNetCore.ReDoc/Swashbuckle.AspNetCore.ReDoc.csproj
- src/Swashbuckle.AspNetCore.ReDoc/index.html
- src/Swashbuckle.AspNetCore.ReDoc/package-lock.json
- src/Swashbuckle.AspNetCore.ReDoc/package.json
- Updated ReDoc to version 2.0.0-rc.1. This enables OpenAPI 3.0 support.
- Added documentation in README-v5 for ReDoc options.
- Removed ReDoc options that are not in 2.0.0-rc.1. (While doing this I also noticed why the "SupressWarnings" do not work in pre version 5 Swashbuckle, it should be "SuppressWarnings".)
- Added extension methods for ReDoc options.
Since ReDoc is not yet in stable 2.0 this PR should (if considered ok) be merged before Swashbuckle 5.0 is released (since ReDoc 1.x does not work with OpenAPI 3) or when ReDoc 2.0 is released.
> ReDoc 2.0.0-rc.1

- src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Generator/SwaggerGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/TestFixtures/Fakes/FakeController.cs
Currently all 3xx responses are described as "Redirect", but 304 should be "Not Modified".
> Return "Not Modified" as description for 304 Response

- src/Swashbuckle.AspNetCore.SwaggerUI/index.html
- test/WebSites/OAuth2Integration/Startup.cs
Hello, 
There is a bug when you activate DeepLinking and load the swagger ui with it.
To reproduce in the oauth2 sample activate deeplinking run it and go to http://localhost:50581/resource-server/swagger/index.html#/Products/get_products then try to authenticate.
Would be nice to have it also  for version 4 as we can't use version 5.0.0-beta because https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters is not available with the breaking changes.
Thanks
> Remove hash from redirect uri

- src/Swashbuckle.AspNetCore.SwaggerGen/Generator/OpenApiAnyFactory.cs
An enum of type short leads to a casting error. In order to cast a short enum to int, one must unbox first.
If you wish to fix it in a different way, just throw this pull request away.
https://stackoverflow.com/questions/7648871/directly-unboxing-a-boxed-int-to-short
I wanted to quickly address the issue in test Apply_SetsPropertyExample_FromPropertyExampleTags, but failed to get the test right in a first attempt. Maybe you have an idea how to construct a test case.
> failing type conversion of short enums

- src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SwaggerGenerator.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsOperationFilter.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/Fakes/FakeController.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/Fakes/XmlAnnotatedController.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Generator/SwaggerGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsOperationFilterTests.cs
While porting an application from version 4.0.1 to 5.0.0-rc2, I found that the `Required` property was not being set to true for the request body if bound to a controller parameter, as well as the `Description` property not being set to the XML documentation for such a parameter.
This PR fixes both of these cases.
This was probably broken by the body moving from being a parameter in the V2 schema to a distinct concept in the V3 schema.
> Fix body parameter handling

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGen/SchemaGenerator.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGen/SchemaGeneratorTests.cs
Array of the nullable types like `DateTime?[]` cause OutOfBoundException in SwaggerGenerator.
This PR fixes it.
> Fixes array of nullable type causes out of bound exception

- src/Swashbuckle.AspNetCore.Cli/Swashbuckle.AspNetCore.Cli.csproj
- test/Swashbuckle.AspNetCore.Cli.Test/Swashbuckle.AspNetCore.Cli.Test.csproj
- test/WebSites/CliExample/CliExample.csproj
- Bump to netcoreapp2.1, since this is minimal version supported by .NET Tools
- Name command as swagger (just so package could be used both ways hopefully)
Building and packaging
```
dotnet pack -c release -o ../artifacts /p:VersionSuffix=dev
```
Not sure how to propely integrate into existing build
Testing locally.
```
dotnet tool install --add-source <path-to-artifacts>artifacts\  Swashbuckle.AspNetCore.Cli
```
Closes #761
More information:
- https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create
- https://github.com/dotnet/core/tree/master/samples/dotnetsay
> Add swagger dotnet tool

- README.md
- test/WebSites/CliExample/CliExample.csproj
- test/WebSites/CliExample/dotnet-tools.json
As per @domaindrivendev description, created explanation for the usage of global tool.
I take liberation and place explicit version of 5.0.0 in the CliExample, since this is required to have proper tool configuration for restoring. So if you want to release 5.0.0-rc3 then that place should be changed.
> Add description for usage of global tool

- src/Swashbuckle.AspNetCore.Swagger/SwaggerMiddleware.cs
Use _options instead of options in order to get rid of possible nullref.
> Fix possible NullReferenceException

- src/Swashbuckle.AspNetCore.ApiTesting.Xunit/Swashbuckle.AspNetCore.ApiTesting.Xunit.csproj
- test/Swashbuckle.AspNetCore.Annotations.Test/Swashbuckle.AspNetCore.Annotations.Test.csproj
- test/Swashbuckle.AspNetCore.ApiTesting.Test/Swashbuckle.AspNetCore.ApiTesting.Test.csproj
- test/Swashbuckle.AspNetCore.Cli.Test/Swashbuckle.AspNetCore.Cli.Test.csproj
- test/Swashbuckle.AspNetCore.IntegrationTests/Swashbuckle.AspNetCore.IntegrationTests.csproj
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Swashbuckle.AspNetCore.SwaggerGen.Test.csproj
- test/WebSites/TestFirst.IntegrationTests/TestFirst.IntegrationTests.csproj
Currently both XUnit 2.2.0 and 2.4.0 are pulled in. 
Simply pull in exclusively 2.4.1.
> Consolidate XUnit to 2.4.1

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SchemaRepository.cs
Some manipulation requires us to have access to a mapping from Type to SchemaID/Schema.
Unless there is a better way to find the SchemaID associated to a Type, it would be much helpful to restore `SchemaRepository.TryGetIdFor`.
For example, we use this to implement discriminator for Polymorphic schema.
> Restore SchemaRepository.TryGetIdFor

- src/Swashbuckle.AspNetCore.Newtonsoft/DependencyInjection/NewtonsoftServiceCollectionExtensions.cs
- src/Swashbuckle.AspNetCore.Newtonsoft/NewtonsoftApiModelResolver.cs
- src/Swashbuckle.AspNetCore.ReDoc/ReDocBuilderExtensions.cs
- src/Swashbuckle.AspNetCore.ReDoc/ReDocMiddleware.cs
- src/Swashbuckle.AspNetCore.Swagger/DependencyInjection/SwaggerBuilderExtensions.cs
- src/Swashbuckle.AspNetCore.Swagger/SwaggerMiddleware.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/Application/SwaggerGenServiceCollectionExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonApiModelResolver.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIBuilderExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs
Removed duplicate constructors where one of them used 'IOptions' and one did not.
Having duplicate constructors creates ambiguities for some IoC containers which can result in them not being able to resolve some Swashbuckle services. Furthermore, this change helps decouple these classes from configuration infrastructure and moves it closer to where it belongs.
> Removed duplicate constructors where one of them used 'IOptions'

- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsTextHelper.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsTextHelperTests.cs
Changes on XmlCommentsTextHelper and XmlCommentsTextHelperTests. Related issues : #1151, #1265 and, possibly, #1026.
Decode itself is done by System.Net.WebUtility.HtmlDecode() method. Calling it after NormalizeIndentation and Humanize functions seems interesting to avoid entities like `&lt;` and `&gt; `to break valid xml before calling Humanize(..).
> fix: decode xml comments

- README.md
`ApiModel` was removed from `SchemaFilterContext` by https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1411.
This PR updates README.md to reflect this change.
> Readme apimodel

- package-lock.json
- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptions.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptionsExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/package-lock.json
- src/Swashbuckle.AspNetCore.SwaggerUI/package.json
- test/WebSites/OAuth2Integration/AuthServer/Config.cs
- test/WebSites/OAuth2Integration/Startup.cs
- Added support for [PKCE](https://tools.ietf.org/html/rfc7636) with the Autorization Code flow.
- This makes the Authorization Code flow more secure because the code can only be used by the client that provided the code_challenge on the /authorize request. It's the recommended way for [Browser-Based Applications](https://www.identityserver.com/articles/change-in-recommendations-for-browser-based-applications)
Fixes #999 
- I've update the [OAuth2IntegrationSample](https://github.com/lurumad/Swashbuckle.AspNetCore/tree/feature/pkce/test/WebSites/OAuth2Integration) flow to use an interactive confidential client (Code with PKCE).
Regards!
> Add support to PKCE for SwaggerUI & update OAuth2Integration sample #999

- README.md
So happy with the 5.0.0 release ! Thanks !
While looking at it, I found that the code examples were still refering the 5.0.0-rc5 version rather than the 5.0.0 version.
Here are the fixes to the readme file to fix this.
> Additional readme updates to coincide with 5.0.0 releases

- README.md
In a code example there was a missing semicolon from the end of one line.
> Fixed simple typo in README

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
Motivation
------------
The properties dictionary is not being checked prior to adding a discriminator property, resulting in a key exception
Modification
-------------
- Checked the properties dictionary keys before adding a new key
> Fix dictionary key exception regarding GeneratePolymorphicSchemas

- src/Swashbuckle.AspNetCore.ReDoc/ReDocBuilderExtensions.cs
- src/Swashbuckle.AspNetCore.Swagger/DependencyInjection/SwaggerBuilderExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIBuilderExtensions.cs
Provide capability to ignore existing SwaggerOptions/SwaggerUiOptions which would allow you to expose different Swagger endpoints & UI URLs.
I've added OpenAPI 3.0 support to https://github.com/tomkerkhove/promitor but still support the old Swagger 2.0 approach.
With this approach, we have:
- Swagger UI 2.0 on `/swagger/index.html` which serves these Swagger doc endpoints
- Swagger 2.0 on `/swagger/v1/swagger.json` (serialized as v2)
- OpenAPI 3.0 on `/api/v1/docs.json`
- OpenAPI UI 3.0 on `/api/docs/index.html` which serves these OpenAPI doc endpoints
- OpenAPI 3.0 on `/api/v1/docs.json`
This allows me to have the new approach side-by-side with the deprecated approach.
When we're doing this:
```csharp
app.UseOpenApi(setupAction => setupAction.RouteTemplate = …
```
> Provide capability to ignore existing SwaggerOptions/SwaggerUiOptions

- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs
Using a route prefix including special characters leads the swagger link to use the wrong index.html.
Instead of using the index.html from the swaggerui project, it uses the index.html from the swagger-ui-dist package (https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html), and so usually opens the pet store sample.
This is due to the raw route prefix being passed in as regex-pattern, without being escaped properly.
The app config I've tried to use:
```c#
app.UseSwagger(c => { c.RouteTemplate = "$/swagger/{documentName}/swagger.json"; });
app.UseSwaggerUI(c =>
{
c.RoutePrefix = "$/swagger";
c.SwaggerEndpoint("/$/swagger/v1/swagger.json", "pineapple api v1");
});
```
> escape swaggerui route prefix when used in regexes

- src/Swashbuckle.AspNetCore.Annotations/Swashbuckle.AspNetCore.Annotations.csproj
The `...Annotations` project is currently being published to NuGet without a repository link.
* https://www.nuget.org/packages/Swashbuckle.AspNetCore.Annotations/
My team makes use of [renovate-bot](https://github.com/renovatebot/renovate) for automated dependency updates, which has configuration to group monorepo dependencies into single update requests. For Swashbuckle, this is currently relying on the [source URL prefix](https://github.com/renovatebot/presets/blob/master/packages/renovate-config-monorepo/package.json#L15).
> add repo to Annotations project nuspec

- README.md
- src/Swashbuckle.AspNetCore.Cli/Program.cs
Since `IWebHost` is deprecated, the library should support `IHost`.
Fixes #1614.
I have checked that the fix works on one of my production apps.
> Support IHost in CLI

- src/Swashbuckle.AspNetCore.SwaggerGen/Application/SwaggerGenServiceCollectionExtensions.cs
Avoid error if someone has already registered the service in app startup.
> Use TryAdd to register services

- .gitignore
- README.md
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsSchemaFilter.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/FakeControllerWithXmlComments.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Swashbuckle.AspNetCore.SwaggerGen.Test.xml
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsSchemaFilterTests.cs
- test/WebSites/Basic/Controllers/CrudActionsController.cs
Fixes #1628.
I ensure the example type is the correct type and not always a string.
Includes unit tests and updated Readme.
> Add examples to XML params

- src/Swashbuckle.AspNetCore.ApiTesting/OpenApiSchemaExtensions.cs
Improving data types on Swashbuckle.AspNetCore.ApiTesting to check and allow integer, datetime, byte, guid and double.
This change is based on:
https://swagger.io/specification/
> improving data types

- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs
Fixes https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1688#issue-comment-box
If you want the swagger ui served from the root path, you can set de RoutePrefix to an empty string. However, behind a reverse proxy and a appbasepath set, the request path could be empty (instead of a /) 
This tiny fix solves these edge cases.
> Fixed redirect when using empty RoutePrefix

- README.md
Fixes  a tiny typo (demonstratd instead of demonstrated)
> fix typo in README.MD

- src/Swashbuckle.AspNetCore.Swagger/SwaggerMiddleware.cs
- src/Swashbuckle.AspNetCore.Swagger/SwaggerOptions.cs
This pull request let users use yaml in addition to json.
Simply replace json with yaml
here
`app.UseSwaggerUI(x =>
{
x.SwaggerEndpoint("/swagger/v1/swagger.yaml", "Zeipt Dashboard API");
});`
And you're set. Requests to "/swagger/v1/swagger.json" will still return the json file, and requests to "/swagger/v1/swagger.yaml" will return the yaml file if you continue to use json.
I've made this change because a client I have use yaml for their API documentation and referring them to my Swashbuckle json file every time I made an API change was not satisfactory and the yaml file was to be preferred.
> Adding support for yaml in ui

- src/Swashbuckle.AspNetCore.Newtonsoft/SchemaGenerator/JsonPropertyExtensions.cs
- src/Swashbuckle.AspNetCore.Newtonsoft/SchemaGenerator/NewtonsoftDataContractResolver.cs
- test/Swashbuckle.AspNetCore.Newtonsoft.Test/Fixtures/AdditionalPropertyJsonContractResolver.cs
- test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
Properties serialized with Newtonsoft do not have to have a declaring type, e.g. if they are provided by a custom contract resolver. This commit fixes NullReferenceException issues on the DeclaringType property (that is also marked as CanBeNull by Newtonsoft).
> Fix: Newtonsoft Handle Properties without DeclaringType

- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs
Fix: redirect to index.html in proxy environments with RoutePrefix set to an empty string.
> Fix: redirect to index.html in proxy environments with empty RoutePrefix

- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs
Add case insensitive option for RoutePrefix url match.
> Fix automatic redirection to default swagger Pet Store when RoutePrefix don't match the URL case

- README.md
Small fix to example under _Describing Discriminators_.
> Small fix to "Describing Discriminators" example in README.md

- src/Swashbuckle.AspNetCore.ReDoc/ReDocMiddleware.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/ReDocIntegrationTests.cs
Fixes #1902, making the check for {routeprefix}/index.html case insensitive like /{routeprefix}.
I also noticed the regex escape in the redirect url check. Should that also be applied here?
> Ignore case when serving /index.html in redoc

- README.md
- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptions.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptionsExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/index.html
- test/WebSites/CustomUIConfig/Startup.cs
This will allow us to define interceptors without having to replace the
entire index.html for simple use cases such as adding XSRF tokens to all
requests. The functions are parsed and passed to the SwaggerUI
configuration without using eval().
> Added possibility to define client-side interceptors

- ci/test.ps1
- test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/SystemTextJsonSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsSchemaFilterTests.cs
- test/Swashbuckle.AspNetCore.TestSupport/Attributes/UseInvariantCultureAttribute.cs
- test/Swashbuckle.AspNetCore.TestSupport/Swashbuckle.AspNetCore.TestSupport.csproj
Some tests are failing if executed with `CurrentCulture`, where decimal separator is different from period.
For example (`CultureInfo.CurrentCulture` is "ru-RU" where comma is decimal separator):
> Set invariant culture in unit tests

- README.md
This updates README.md to remove the statement (wrong since v4) that `IFormFile` support requires using the separate .Filters repo, and also to briefly explain up-front that `IFormFile` must be used without `FromForm`.
@domaindrivendev although  #1183 is now closed (I think maybe for other reasons, such as that the discussion under the issue had gone back on to the repeated debate about `IFormFile` and `FromForm`, and that after the delay in your being able to reply, I also hadn't been able to get back to this for quite some time either), but the minor changes to the documentation which I suggested there (and which you kindly agreed sounded sensible, back in Jan.) still remain needed.
I have included some of the explanation about `IFormFile` and `FromForm` from your own info about this …
> Important, straightforward README update: IFormFile support not in .Filters repo + IFormFile requires no FromForm

- Swashbuckle.AspNetCore.sln
- ci/build.ps1
- src/Directory.Build.props
- src/Swashbuckle.AspNetCore.Annotations/Swashbuckle.AspNetCore.Annotations.csproj
- src/Swashbuckle.AspNetCore.ApiTesting.Xunit/Swashbuckle.AspNetCore.ApiTesting.Xunit.csproj
- src/Swashbuckle.AspNetCore.ApiTesting/Swashbuckle.AspNetCore.ApiTesting.csproj
- src/Swashbuckle.AspNetCore.Cli/Swashbuckle.AspNetCore.Cli.csproj
- src/Swashbuckle.AspNetCore.ReDoc/Swashbuckle.AspNetCore.ReDoc.csproj
- src/Swashbuckle.AspNetCore.Swagger/Swashbuckle.AspNetCore.Swagger.csproj
- src/Swashbuckle.AspNetCore.SwaggerGen/Swashbuckle.AspNetCore.SwaggerGen.csproj
- src/Swashbuckle.AspNetCore.SwaggerUI/Swashbuckle.AspNetCore.SwaggerUI.csproj
- src/Swashbuckle.AspNetCore/Swashbuckle.AspNetCore.csproj
This change make any project in the `src/` folder to import `version.props` file
See https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#directorybuildprops-and-directorybuildtargets
`build.ps1` modified to pack only folders in `src\` directory.
> Consolidate usage of version using Directory.Build.props

- README.md
Thanks for your project!  When using the example in the README to set a custom swagger path for the UI, I found that it didn't work.  I found that an extra line of config was necessary to get it working.
This is a one-line PR to add in the missing line I needed to get custom paths working.
> Update README.md example for setting custom swagger path

- test/WebSites/OAuth2Integration/ResourceServer/Swagger/SecurityRequirementsOperationFilter.cs
`SecurityRequirementOperationFilter` should not only respect `AuthorizeAttribute` on the method, but also on the class, so additionally read the attributes from the declaring type.
Then use the configured `AuthorizationOptions` to retrieve the actual Policy that is named in the `AuthorizeAttribute`.
Then analyze the policy and find all scope requirements to figure out the actual required scopes.
> Enhance SecurityRequirementOperationFilter

- src/Swashbuckle.AspNetCore.ReDoc/ReDocBuilderExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIBuilderExtensions.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/ReDocIntegrationTests.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerUIIntegrationTests.cs
- test/WebSites/MultipleVersions/MultipleVersions.csproj
- test/WebSites/MultipleVersions/Startup.cs
Last changes to Swashbuckle returned back old options' mutation bug that prevents generating SwaggerUI and Redoc pages for separate swagger document versions.
Authors suggest to use a different overload of UseSwaggerUI and UseRedoc here: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1996
But I still think that singleton options mutation is misleading and users don't expect that. So in this PR I restored the old behaviour and also added new tests to ensure it will not break again.
> Handle multiple document versions in SwaggerUI and Redoc

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/MemberInfoExtensions.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.TestSupport/Fixtures/TypeWithNullableContext.cs
This change only affects the logic in finding compiler annotated null attributes when using the "SupportNonNullableReferenceTypes" option.
More information about roslyn nullable metadata can be found here https://github.com/dotnet/roslyn/blob/main/docs/features/nullable-metadata.md
This PR should fix #2017 and probobly #1487
> Fixed problem with finding nullable attribute in nested types because of roslyn optimizations

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/JsonIgnoreAnnotatedType.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Swashbuckle.AspNetCore.SwaggerGen.Test.csproj
This PR corrects https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1899
I updated the SwaggerGen test project to .Net 5, so JsonIgnoreAnnotatedType.cs can use JsonIgnoreAttribute.Condition. If you'd prefer, I can create a separate .Net 5 project and create a new class there to validate this fix (and leave JsonIgnoreAnnotatedType.cs alone to validate passivity).
Let me know if you'd like me to change anything, thanks!
> Fix issue 1899

- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptions.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptionsExtensions.cs
This will give a developer the option to have "Try It Out" enabled on
all operations. It can be tedious at times to have to click the button
for each operation if you are testing many things out in the Swagger UI.
Example:
```c#
app.UseSwaggerUI(options =>
{
options.EnableTryItOutByDefault();
}
```
> Add option to enable try it out by default

- src/Swashbuckle.AspNetCore.Cli/Program.cs
Fixes #2117
The main command "tofile", if it has arguments that are enclosed in double quotes, will receive them as independent elements in the args array.  When the call to dotnet exec is made to invoke the subcommand "_tofile", if there are any arguments that contain spaces, they will now be regarded as multiple arguments and the subcommand run will have a different set of arguments, ones that do not match the users' intentions.
Uses the existing EscapePath to enclose those parameters that contain spaces with double quotes.  The result is that if the paths that are arguments for the "tofile" command (startupassembly or --output) contain spaces, they should now be seen by the subcommand the same as they were in the main command.
> Fixes #2117

- src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenOptionsExtensions.cs
Fix typo in XML comment for `IncludeXmlComments()` method in `SwaggerGenOptionsExtensions`.
> Fix typo in XML comment in SwaggerGenOptionsExtensions.cs

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/OpenApiAnyFactory.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsSchemaFilter.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/XmlAnnotatedType.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/OpenApiAnyFactoryTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Swashbuckle.AspNetCore.SwaggerGen.Test.xml
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsSchemaFilterTests.cs
Addresses a reversion in closed issue:
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1768
XML Comments for String properties with <example> tags that contain null were showing the string "null" 
For the string property Subtitle:
```C#
/// <summary>
/// The Subtitle of the book
/// </summary>
/// <example>null</example>
public string Subtitle { get; set; }
```
Expected:
```json
{
"generatedAt": "2021-06-28T02:12:19.2734596Z",
"id": 419200,
"title": "The Moonstone",
"subtitle": null
}
```
Actual:
```json
{
"generatedAt": "2021-06-28T02:12:19.2734596Z",
"id": 419200,
"title": "The Moonstone",
"subtitle": "null"
}
```
This was initially fixed in PR https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1866 but broke again in 6.0.1 when swagger-ui fixed a bug …
> Nullable strings showing string null in examples

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGeneratorOptions.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
- test/Swashbuckle.AspNetCore.TestSupport/ApiExplorer/ApiDescriptionFactory.cs
Fixes https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2165.
Part of https://github.com/dotnet/aspnetcore/issues/34514.
> Support setting operation IDs from EndpointName metadata

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGeneratorOptions.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
- Handle null EndpointMetadata
- Added test
Fixes https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2194
> Fixed regression when looking for an operation id

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/ApiParameterDescriptionExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
- For non-controllers, change the logic to look for the IsRequired flag on the ApiParameterDescription instead of the fallback logic. This is to avoid potentially breaking existing behavior for controller based API descriptions. In theory, this logic could be changed for controllers since MVC does use that logic but that's a behavior change that would likely need to be opted into.
~TODO: Add tests.~
> Change how IsRequired for parameter descriptions work

- src/Swashbuckle.AspNetCore.Cli/HostFactoryResolver.cs
- src/Swashbuckle.AspNetCore.Cli/HostingApplication.cs
- src/Swashbuckle.AspNetCore.Cli/Program.cs
- test/Swashbuckle.AspNetCore.Cli.Test/Swashbuckle.AspNetCore.Cli.Test.csproj
- test/Swashbuckle.AspNetCore.Cli.Test/ToolTests.cs
- The HostFactoryResolver is [shared source](https://github.com/dotnet/runtime/blob/7ed5a67c0bbb48bdce3cfd962e333c8f7db047a4/src/libraries/Microsoft.Extensions.HostFactoryResolver/src/HostFactoryResolver.cs) that is used by tools to resolve the entry point and service provider from applications that use Microsoft.Extensions.Hosting. It has been updated to handle a couple of new patterns introduced in .NET 6 and this change uses it as a fallback after detecting the other patterns. I've copied the source into this project since I didn't want to add a new nuget feed as a requirement to build this application. We'll need to keep this file in sync if there are changes.
- I had to make changes to make the shared source support C# 7.3 (and remove nullable support). I'd prefer to fix it so that …
> Added HostFactoryResolver to detect new application patterns

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGeneratorOptions.cs
MVC uses `LastOrDefault` to pick the most recently inserted element.
https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/Routing/ActionEndpointFactory.cs#L345-L347
> Update filter behavior to match MVC pattern

- src/Swashbuckle.AspNetCore.Swagger/DependencyInjection/SwaggerBuilderExtensions.cs
This updates the default pattern of `MapSwagger` to match the [default pattern](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.Swagger/SwaggerOptions.cs#L19) that is used in `UseSwagger`. This allows YAML support to be enabled by default when using `MapSwagger` as it is in `UseSwagger`.
> Update 'MapSwagger' default behavior to match the default route pattern for 'UseSwagger'

- README.md
Hello,
I've added the following text: "or add `<NoWarn>1591</NoWarn>` to the `<PropertyGroup>` section of your .csproj project file" to the **Include Descriptions from XML Comments**.
This could be helpful to people using text editors such Visual Studio Code.
Let me know If there's something you would like me to change.
🥂
> Improve readme 'Include Descriptions from XML Comments' section

- src/Swashbuckle.AspNetCore.SwaggerUI/index.html
- test/WebSites/CustomUIIndex/Swagger/index.html
Fixes #1854
URL JS API: https://caniuse.com/url (no IE 11, but there are already other non-IE 11 usages like [startsWith()](https://caniuse.com/mdn-javascript_builtins_string_startswith))
> Use the URL API to create a location-relative path to "oauth2-redirect.html

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/ApiDescriptionExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
The current `RelativePathSansQueryString` method causes problems with the approach that minimal APIs use for setting an endpoint names.
With an endpoint like:
```csharp
app.MapGet("/bar/{foo?}", (string foo) => ...);
```
Will produce a `relativePath` that looks something like `/bar/{foo` which is incorrect.
To mitigate this, I used a negative lookahead regular expression to only split on the query string part and to ignore optional parameters.
`Regex.Split` is not as performant as a `string.Split` but I wasn't sure what other alternatives might be best here.
Is there a particular reason that we remove the query string part? There might be another alternative to approach here (e.g. removing the query string with the existing strategy in another codepath).
> Fix parsing of optional params in route

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/TypeWithPropertiesSetViaConstructor.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
It looks like STJ now supports deserialization of readonly properties that are set via constructor
> For STJ - don't set readonly if set via constructor

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/ApiDescriptionExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
Fixes https://github.com/dotnet/aspnetcore/issues/36413.
This fix expands on the changes made in https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2209.
Currently, the route constraints that are included in the route template path are included in the generated schema which breaks things like the `curl` command generated in the UI. This resolves that issue by stripping out constraints/qualifiers from the path.
Note that there is work tracked in https://github.com/dotnet/aspnetcore/issues/36525 to ensure that these route constraints show up in the schema.
> Remove constraints from route parameters in path

- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIBuilderExtensions.cs
Updated the defaults for `IApplicationBuilder.UseSwaggerUI` to better match the [defaults of `IServiceCollection.AddSwaggerGen`](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/ConfigureSwaggerGeneratorOptions.cs#L51) so that the displayed document name in the Swagger UI matches the actual document name and title.
We intend to change the default webapi project template code in ASP.NET Core in .NET 6.0 to simply use the Swashbuckle defaults and this change makes the UX align more clearly.
> Ensure UseSwaggerUI & AddSwaggerGen defaults match

- src/Swashbuckle.AspNetCore.Annotations/AnnotationsDocumentFilter.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsDocumentFilter.cs
I've come across this issue with `Microsoft.AspNetCore.Grpc.Swagger` lib, which is in preview. That lib has [Order of GrpcHttpApiDescriptionProvider](https://github.com/aspnet/AspLabs/blob/7ddba9bbf566138dac11d463c8cbed73ee94f806/src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.Swagger/Internal/GrpcHttpApiDescriptionProvider.cs#L27) set to -900, which is greater than asp.net default -1000. Hence it inserts non `ControllerActionDescriptor`s after them. It causes NRE.
I didn't find any reason why it's a `SkipWhile` and not a `Where` clause.
> Fixed NRE when non ControllerDescriptor presented not at the beginningof the collection

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/ApiParameterDescriptionExtensions.cs
- test/Swashbuckle.AspNetCore.Annotations.Test/AnnotationsRequestBodyFilterTests.cs
- test/Swashbuckle.AspNetCore.TestSupport/ApiExplorer/ApiDescriptionFactory.cs
Use the `IParameterInfoParameterDescriptor` interface, where available, rather than `ControllerParameterDescriptor` so that parameter info is available on endpoints that are not MVC Controllers.
Relates to https://github.com/dotnet/aspnetcore/issues/36438.
> Use IParameterInfoParameterDescriptor for parameter info

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/ApiDescriptionExtensions.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
The current implementation can, for example, corrupt paths which
legitimately contain equals signs which are not indicating a default
value. This can come up in OData or when simulating matrix parameters.
Other contributors have taken a swing at this problem, but I'm hoping that
the small size of this solution will help its acceptance.
Fixes #2239
Fixes #2247
Fixes #2245
Fixes #2294
> Filter Out Qualifiers Only between Curly Braces

- src/Swashbuckle.AspNetCore.Swagger/DependencyInjection/SwaggerBuilderExtensions.cs
This fixes #1705 
So it is easier to add Authentication to the swagger.json route
> Let MapSwagger return IEndpointConventionBuilder

- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsTextHelper.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsTextHelperTests.cs
`<c></c>` tags are currently [replaced](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsTextHelper.cs#L11) by [`{}`](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsTextHelper.cs#L95), but this is [rather old code](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/85d4d09707679b5a04c7a6b3770820d24b786127#diff-233d46370aa00ef71a1979e91ebef89acdf75f0d7280e89d424eb207eeff6002R9), and I couldn't find anything about this being standard practice in OpenAPI/Swagger (the only mention I could find of `{}` was in relation to [URL path parameters](https://swagger.io/docs/specification/paths-and-operations/)). Redoc …
> Replace <c></c> with Markdown backticks instead of curly brackets

- Swashbuckle.AspNetCore.sln
- src/Swashbuckle.AspNetCore.Annotations/AnnotationsOperationFilter.cs
- test/Swashbuckle.AspNetCore.Annotations.Test/AnnotationsOperationFilterTests.cs
- test/Swashbuckle.AspNetCore.Annotations.Test/Swashbuckle.AspNetCore.Annotations.Test.csproj
Also consider the `EndpointMetadata` for operations when targeting .NET 5 and later for Swagger annotation attributes. This allows attributes applied to ASP.NET Core 6 Minimal Actions to be discovered.
I ran into this issue while migrating an ASP.NET Core 5 demo project with various customisations for the Swagger documentation to use ASP.NET Core 6 Minimal Actions using a daily build of the .NET 6 RC1 SDK (https://github.com/martincostello/api/pull/576, specifically this commit https://github.com/martincostello/api/pull/576/commits/75b086c171bd1d494c76df5f34cffc7e92c8912d in the `ApiModule` class for the relevant parts, for example [this endpoint](https://github.com/martincostello/api/blob/75b086c171bd1d494c76df5f34cffc7e92c8912d/src/API/ApiModule.cs#L47-L65)).
~I wasn't sure specifically …
> Consider EndpointMetadata for annotations

- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptions.cs
The examples provided in XML comments for `RequestInterceptorFunction` and `ResponseInterceptorFunction` didn't work because [`parseFunction`](https://gist.github.com/lamberta/3768814) in general cannot handle lambdas (it requires that the function body must be enclosed in `{}`, and parameters list be enclosed in `()`, neither of which is definitively true for lambdas). Fixed by changing the example to a function expression.
> Fix XML comments on Swagger UI interceptors

- src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenOptionsExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGeneratorOptions.cs
Typically, this would be done by DocumentFilters, but since the schemas are sorted after filters are applied, it's impossible to do this. Commit 224a0843bf5faa180ebd9a93d05e35f53c76a5ee moved the schema sorting to after filter application.
This PR adds a new SchemaComparer SwaggerGeneratorOptions property that will handle last-mile schema sorting.
> Enable custom schema sorting

- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptions.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptionsExtensions.cs
- test/WebSites/OAuth2Integration/Startup.cs
I wanted to set default username for OAuth2 password flow.
Unfortunately, its not exposed.
Added possibility to do so.
> Add default username for OAuth2 password flow.

- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/Swashbuckle.AspNetCore.SwaggerUI.csproj
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerUIIntegrationTests.cs
This is a flaky area that went through a lot of issues - so (for now) reveting to the tried n tested regex based approach. Also added some more tests.
> Revert to regex approach for swagger-ui routing + improve test cov

- src/Swashbuckle.AspNetCore.Cli/Program.cs
There was a typo in the message after generating Swagger. It had "succesfully" with one S instead of two "successfully"
> style: typo succesfully to successfully

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/MemberInfoExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.TestSupport/Fixtures/TypeWithNullableContext.cs
This PR fixes nullabillity issues with Dictionaries like:
```
public Dictionary<string, string>? NullableDictionaryWithNonNullableContent { get; set; }
public Dictionary<string, string> NonNullableDictionaryWithNonNullableContent { get; set; } = default!;
public Dictionary<string, string?> NonNullableDictionaryWithNullableContent { get; set; } = default!;
public Dictionary<string, string?>? NullableDictionaryWithNullableContent { get; set; }
```
Fixes #1849
> Fixed nullabillity problems with dictionaries

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/ApiDescriptionExtensions.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/ApiDescriptionExtensions/ApiDescriptionExtensionsTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/TestMinimalApiMethod.cs
Add the ability to discover MethodInfo for ASP Net Core Minimal API delegates.
> Add MethodInfo discovery for Minimal API

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
As part of the work outlined in https://github.com/dotnet/aspnetcore/issues/40676 and implemented in https://github.com/dotnet/aspnetcore/pull/41238, we're experimenting with providing a package that allows users to generate and modify `OpenApiOperation` metadata directly on endpoints.
In this new workflow, a user can annotate their endpoint like so:
```csharp
app.MapGet("/foo", () => ...)
.WithOpenApi();
```
Which will generate the `OpenApiOperation` directly and add it to the endpoint metadata. Users can also do:
```csharp
app.MapGet("/foo", () => ...)
.WithOpenApi(operation => {
return modifyMyOperation(operation)
});
```
Which will add an `OpenApiOperation` to metadata with the modifications that the user provides.
This PR checks to see if there already exists `OpenApiOperation` …
> Support prebuilt OpenApiOperation in EndpointMetadata

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
- test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.TestSupport/Fixtures/TypeWithValidationAttributes.cs
- test/Swashbuckle.AspNetCore.TestSupport/Fixtures/TypeWithValidationAttributesViaMetadataType.cs
Potentially fixes #2428
When using RequiredAttribute with AllowEmptyStrings=false on a string, a minLength:1 will be added to the schema to inform that the string must not be empty. If any MinLength attributes are set, they will override this value.
> #2428 set minLength for RequiredAttribute.AllowEmptyStrings=false

- src/Swashbuckle.AspNetCore/Swashbuckle.AspNetCore.csproj
Update to the latest release of M.E.ApiDescription.Server package to:
- Address issues with resolving the ServiceProvider in the new host model like https://github.com/dotnet/aspnetcore/issues/40577
- Bring in bug fixes like https://github.com/dotnet/aspnetcore/pull/36355 and https://github.com/dotnet/aspnetcore/pull/39293
> Update M.E.ApiDescription.Server version to 6.x release

- src/Swashbuckle.AspNetCore.Swagger/IAsyncSwaggerProvider.cs
- src/Swashbuckle.AspNetCore.Swagger/SwaggerMiddleware.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/DocumentProvider.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenServiceCollectionExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGeneratorOptions.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
Addresses part of https://github.com/dotnet/aspnetcore/issues/39761 and part of https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1661.
We've been exploring the possibility of automatically generating `OpenApiSecuritySchemes` by examining authentication/authorization state in an ASP.NET Core app and auto-generating the appropriate annotations. 
- Adds an `IAsyncSwaggerProvider` interface and implementations of `GetSwaggerAsync` to `SwaggerGenerator` to support making async calls to the authentication system
- Adds a new `SecuritySchemesSelector` to `SwaggerGeneratorOptions` for deriving `OpenApiSecuritySchemes` from `AuthenticationSchemes`
> Add support for SecuritySchemesSelector and default implementation

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
Designed to be coupled with https://github.com/dotnet/aspnetcore/pull/42169.
> Use schemas generated by Swashbuckle for built-in operations

- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptions.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptionsExtensions.cs
> Updated the comments around client secret.

- README.md
Minor update in one of the examples in the readme.
> Added missing bracket in README example

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
This PR fixes a null pointer exception when having a API returning av Dictionary containing known keys
(ie a Dictionary<Enum, string>).
The problem was that the code tried to set `schema.AdditionalProperties.Nullable` without first checking if `schema.AdditionalPropertiesAllowed` was true. This resulted in a null point exception since `schema.AdditionalProperties` is null when `schema.AdditionalPropertiesAllowed` is false.
Fixes #2368
> Resolves a null pointer exception when returning a Dictionary containing known keys

- README.md
Adding a note to the instructions for "Conflicting schemaIds" on dealing with nested types.
> Update README.md for nested types custom schemaId support

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Swashbuckle.AspNetCore.SwaggerGen.Test.csproj
fixes https://github.com/dotnet/aspnetcore/issues/40753
fixes https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2548
Adds support for the MinimalAPI operation metadata functions, `WithSummary` and `WithDescription`, including CI changes.
> Add support for `WithSummary` and `WithDescription` metadata

- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsTextHelper.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsTextHelperTests.cs
`<see href="link">text</see>` tags are currently not replaced. The expected format for descriptions in OpenAPI/Swagger is markdown. Redoc does not generate a link for `<see href="link">text</see>` but instead displays the inner text as-is.
This PR changes the behaviour to use GitHub-flavoured markdown, instead - <see href="link">text</see> tags are replaced with a clickable link. Redoc supports this style of links out of the box.
Fixes: #2577
> Replace <see href="link">text</see> with Markdown link format

- src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenOptionsExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsDocumentFilter.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs
This resolves #2717 by switching how comments are tagged using the SwaggerGeneratorOptions
> Resolves #2717

- src/Swashbuckle.AspNetCore.SwaggerGen/Annotations/SwaggerIgnoreAttribute.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/FakeController.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/SwaggerIngoreAnnotatedType.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
Application of the SwaggerIgnoreAttribute suppresses the annotated property during schema generation, without altering the serialization behavior as with JsonIgnoreAttribute.
This is useful in a scenario where you want to capture and reject unhandled properties, without advertising that you accept `additionalProperties` (which is the opposite of what is intended):
```cs
public abstract class RequestBase : IValidatableObject {
[SwaggerIgnore]
[JsonExtensionData]
public IDictionary<string, JsonElement>? UnsupportedProperties { get; set; }
public virtual IEnumerable<ValidationResult> Validate(ValidationContext validationContext) {
if(UnsupportedProperties is { Count: not 0 })
foreach(var entry in UnsupportedProperties)
yield return new ValidationResult($"Unsupported property: {entry.Key}.", …
```
> Added Swashbuckle.AspNetCore.Annotations.SwaggerIgnoreAttribute

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
- test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
> Fix schema generation with allOf inheritance

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/TypeExtensions.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.TestSupport/Fixtures/BaseInterface.cs
Fixes https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2821. Interfaces weren't respected here.
> Correctly respect interfaces in `GetInheritanceChain`

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
Fixes https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2820.
Guess that's totally fine since STJ does support enum keys? It probably did not for some time - but I've checked with .Net 6-8
> Generate Enum-Dictionary-Keys (analogous to Newtonsoft)

- .github/workflows/build.yml
- Directory.Build.props
Add missing suffix to the prerelease label for previews.
> Fix preview package versions

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
- test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
- Do not generate schema models for `Stream` and `PipeReader`.
- Only allocate the array once, rather than on every call.
- Fix warning by removing unused parameter from private method.
Relates to item 3 in https://github.com/dotnet/aspnetcore/issues/44677.
> Handle Stream and PipeReader content types correctly

- Directory.Build.props
- README.md
- package-readme.md
- Add a simple common README file for all NuGet packages.
- Cherry-pick changes from #2715 to update README links from HTTP to HTTPS.
> Add NuGet package READMEs

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
Add an explicit check for supported HTTP methods.
Resolves #2740.
> Throw if unsupported HTTP method used

- src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/ConfigureSwaggerGeneratorOptions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenServiceCollectionExtensions.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/ConfigureSchemaGeneratorOptionsTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/ConfigureSwaggerGeneratorOptionsTests.cs
Fix properties not being copied during clone.
I looked into testing the method directly, but that involved what I thought was too much complication to get `[InternalsVisibleTo]` working. Instead I've added a test which will fail if new properties are added to act as a signpost to update the `DeepCopy()` methods.
- Resolves #2540.
- Resolves #2741.
> Fix configuration properties not being copied

- .github/dependabot.yml
- src/Swashbuckle.AspNetCore.SwaggerUI/package-lock.json
- src/Swashbuckle.AspNetCore.SwaggerUI/package.json
Update to the latest release of Swagger UI.
Resolves #2789.
~~Need to manually check it looks OK before moving out of draft.~~
> Update to Swagger UI v5

- README.md
@martincostello The documentation for the customer document serializer
> Added documentation for ISwaggerDocumentSerializer

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
Adds messages for the Swagger page for 501, 502, 503 and 504 errors.
Closes https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1462
> Adding additional responses when 5XX errors are thrown.

- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsExampleHelper.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsParameterFilter.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsRequestBodyFilter.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsSchemaFilter.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/FakeConstructedControllerWithXmlComments.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/FakeControllerWithXmlComments.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsExampleHelperTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsParameterFilterTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsRequestBodyFilterTests.cs
Fix that XML comment examples do not show up if the type is string and the example contains quotation marks
Resolves #2088
> Fix that XML comment examples do not show up if the type is string and the example contains quotation marks

- src/Swashbuckle.AspNetCore.SwaggerUI/Swashbuckle.AspNetCore.SwaggerUI.csproj
Exclude large `swagger-ui-es*` files, which reduces the size of the SwaggerUI assembly to ~2,145KB.
There's no much else we can remove, swagger-ui itself is large.
Resolves #1646.
> Exclude unused Swagger-UI files

- src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/ConfigureSwaggerGeneratorOptions.cs
Fix the property being copied twice instead of `RequestBodyFilters` being copied at all.
Missed from #2796.
Resolves #2273.
> Fix RequestBodyFilters not being deep copied

- Directory.Build.targets
- test/Swashbuckle.AspNetCore.IntegrationTests/CustomDocumentSerializerTests.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/DocumentProviderTests.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/ReDocIntegrationTests.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerIntegrationTests.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerUIIntegrationTests.cs
- Refactor coverage report for GitHub step summary to try and resolve file conflict issues (and make the code more readable).
- Move test cases that use `TestSite` into the same test collection to stop them being run in parallel with each other.
Contributes to #2836.
> Avoid GitHub step summary file write conflicts

- src/Swashbuckle.AspNetCore.Newtonsoft/SchemaGenerator/NewtonsoftDataContractResolver.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/OpenApiSchemaExtensions.cs
- test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
- Ensure `DateOnly` and `TimeOnly` with for Newtonsoft.Json.
- Add System.Text.Json support for `TimeSpan` and `Version`.
- Add Int128 and UInt128 support.
- Handle `AnnotationsDataType.Upload`.
- Create `AnnotationsDataType` mapping dictionary only once.
Resolves #2611
Relates to #2500
> Extend built-in supported types

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/10_bug_report.yml
- .github/ISSUE_TEMPLATE/20_feature_request.yml
- .github/ISSUE_TEMPLATE/30_question.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/pull_request_template.md
Add GitHub issue and pull request templates.
I've based these on the ones used in [Polly](https://github.com/App-vNext/Polly/tree/main/.github).
Feedback/suggestions welcome.
> Add GitHub issue and PR templates

- .github/workflows/stale.yml
Fix warning due to missing permissions to manage the cache.
See https://github.com/actions/stale/issues/1133#issuecomment-2079373371.
> Fix stale permissions

- .github/workflows/actions-lint.yml
- .github/workflows/build.yml
- .gitignore
- [Attest](https://github.blog/2024-05-02-introducing-artifact-attestations-now-in-public-beta/) the binaries and packages from the build artifacts.
- Update `.gitignore` to ignore MSBuild binary log files and code coverage files.
> Attestation

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
Resolves https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2877
> Fix to make required and nullable properties nullable in schema

- README.md
Update a few outdated links to the Swagger UI repository and add missing extension methods on `SwaggerUIOptions`.
I also thought about adding mentions to the properties directly on `SwaggerUIOptions` (e.g. `HeadContent`) but decided against it for now. Those would need some additinal warnings because otherwise you might undo your previous modifications done by the extension methods again.
> Update Swagger UI section in README

- src/Swashbuckle.AspNetCore.Cli/Program.cs
- test/Swashbuckle.AspNetCore.Cli.Test/ToolTests.cs
The CLI currently uses `File.OpenWrite(path)` (added in https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2677) to create an output stream for the resulting swagger document. This does not delete the existing contents, but instead starts writing from position 0, causing issues if the output is smaller than the previous file content.
I changed it to `File.Create(path)` to make sure any previous content is discarded.
> Existing output file should be deleted/overwritten

- src/Swashbuckle.AspNetCore.ApiTesting.Xunit/Swashbuckle.AspNetCore.ApiTesting.Xunit.csproj
- test/Swashbuckle.AspNetCore.TestSupport/Swashbuckle.AspNetCore.TestSupport.csproj
It caused error messages to printed by Visual Studio when discovering and executing tests. When running tests from a fully clean solution, VS only ends up running a few projects.
Errors such as:
```
Test project Swashbuckle.AspNetCore.ApiTesting.Xunit does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
```
and:
```
Could not find testhost
```
How Test Explorer looks after running all tests on a completely fresh build:
> Fix libraries being handled as test projects

- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsTextHelper.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsTextHelperTests.cs
`<br />`, `<br/>`, and `<br>` tags present in the XML comments end up appearing unchanged in the documentation. The should instead be rendered as new lines.
`Environment.NewLine` produces `\r\n` or `\n` which is standard for most markdown usages.
Similar to https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2392
> Replace `<br />`, `<br/>`, and `<br>` in XML comments with `Environment.Newline`

- src/Swashbuckle.AspNetCore.ReDoc/Swashbuckle.AspNetCore.ReDoc.csproj
- src/Swashbuckle.AspNetCore.Swagger/SwaggerMiddleware.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIJsonSerializerContext.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptions.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/Swashbuckle.AspNetCore.SwaggerUI.csproj
- test/WebSites/CustomUIConfig/Startup.cs
- Extend custom `JsonSerializerContext` to cover objects that might be added to the additional JSON property.
- Speed up local development iterations by only running `npm install` when the `node_modules` directory does not already exist.
- Apply code refactoring suggestions from Visual Studio.
Resolves #2884.
> Fix serialization of AdditionalItems

- Directory.Build.props
- test/Swashbuckle.AspNetCore.Cli.Test/ToolTests.cs
Disable parallel build to see if it fixes file-write conflicts. Relates to #2893.
> Disable parallel build

- Swashbuckle.AspNetCore.sln
- src/Swashbuckle.AspNetCore.Cli/CommandRunner.cs
- src/Swashbuckle.AspNetCore.Cli/HostFactoryResolver.cs
- src/Swashbuckle.AspNetCore.Cli/HostingApplication.cs
- test/Swashbuckle.AspNetCore.Cli.Test/CommandRunnerTests.cs
- test/Swashbuckle.AspNetCore.Cli.Test/Swashbuckle.AspNetCore.Cli.Test.csproj
- test/Swashbuckle.AspNetCore.Cli.Test/ToolTests.cs
- test/WebSites/MinimalAppWithHostedServices/MinimalAppWithHostedServices.csproj
- test/WebSites/MinimalAppWithHostedServices/Program.cs
- test/WebSites/MinimalAppWithHostedServices/Properties/launchSettings.json
- Remove `IHostedService` implementations so the CLI doesn't run hosted services (and then hang/fail).
- Refactor CLI tests to reduce duplication.
- Use newer C# syntax as suggested by Visual Studio.
Supersedes #2713.
Resolves #2712.
/cc @desjoerd
> Do not run IHostedService implementations

- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptions.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerUIIntegrationTests.cs
Fix property casing of Swagger UI interceptor function properties.
Resolves #2906.
> Fix interceptor JSON casing

- Swashbuckle.AspNetCore.sln
- src/Swashbuckle.AspNetCore.Newtonsoft/SchemaGenerator/NewtonsoftDataContractResolver.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerIntegrationTests.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/Swashbuckle.AspNetCore.IntegrationTests.csproj
- test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.TestSupport/Fixtures/TypeWithDefaultAttributes.cs
- test/WebSites/MvcWithNullable/MvcWithNullable.csproj
- test/WebSites/MvcWithNullable/Program.cs
- test/WebSites/MvcWithNullable/Properties/launchSettings.json
- test/WebSites/MvcWithNullable/appsettings.Development.json
- test/WebSites/MvcWithNullable/appsettings.json
- test/WebSites/WebApi/Program.cs
- Fix `SwaggerGeneratorException` if the type of a `[DefaultValue]` does not match the type of the property when using System.Text.Json for serialization.
- Fix schema generation of default values for nullable enums default values.
- Resolve some IDE refactoring suggestions.
- Render the response if an integration test fails for easier debugging.
Regressions caused by changes in #2800 to avoid serializing `object` by providing the type to the serializer.
- Resolves #2885
- Resolves #2904
> Fix generation when [DefaultValue]'s type differs

- README.md
- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptions.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/index.html
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerUIIntegrationTests.cs
- test/WebSites/CustomUIConfig/Startup.cs
Move CSS and JS to parameters, for available to use CDN or custom URL.
> Allow Swagger UI CSS and JS paths to be configurable

- README.md
- src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenOptionsExtensions.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs
- test/WebSites/Basic/Startup.cs
- test/WebSites/GenericControllers/Startup.cs
> Add IncludeXmlCommentsForAssembly convience overload

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/FakeController.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/FakeICompositeMetadataDetailsProvider.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
- test/WebSites/Basic/Controllers/FromFormParamsController.cs
This PR fixes #2919.
In the PR #2610, the project added the SwaggerIgnore attribute, which can ignore Methods from being populated into OpenApi doc or just properties of an object. But it did not added the possibility when the object is one that comes from a FromForm request so I am adding it in this PR
Since this is my first contribution, I am not sure if I have to do a UnitTest to test this behaviour, but in the Basic sample app I inserted a new Endpoint, that you can see the Swagger to see what this PR is addressing.
> Add posibility to Ignore properties in FromForm Request with SwaggerIgnore attribute

- src/Swashbuckle.AspNetCore.Cli/Program.cs
- test/Swashbuckle.AspNetCore.Cli.Test/ToolTests.cs
Fixes #2352
Checks if output directory exists. If it doesn't then it creates before trying to write to the file
> Adding check for existing directory and creating if doesn't exist

- src/Swashbuckle.AspNetCore.Newtonsoft/SchemaGenerator/NewtonsoftDataContractResolver.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
- test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.TestSupport/Fixtures/TypeWithDefaultAttributes.cs
This PR fixes the issues #2920 and  #2937
When serializing the default  value on a Nullable type on System.Text.Json the library was trying to serialize it as the not nullable type, this was not possible on STJ because it gave an exception.
> default null value on nullable types caused errors

- .config/dotnet-tools.json
- .github/workflows/build.yml
Fix the package validation job not failing if there are any issues.
> Fix package validation

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/OpenApiSchemaExtensions.cs
- test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.TestSupport/Fixtures/TypeWithValidationAttributes.cs
- test/Swashbuckle.AspNetCore.TestSupport/Fixtures/TypeWithValidationAttributesViaMetadataType.cs
Fixes #2957
It adds support for Base64String and MinimumIsExclusive and MaximumIsExclusive  properties for RangeAttribute.
The SwaggerUi does not seem to be looking at neither of these properties when validating it
> Adding support for .Net8 Model State Attributes

- src/Swashbuckle.AspNetCore.Annotations/AnnotationsParameterFilter.cs
- test/WebSites/WebApi/Program.cs
- test/WebSites/WebApi/WebApi.csproj
This fixes an issue shown when investigating #2658. Not sure if this fixes it all.
Tested with the project WebApi, if you do not apply the GetCustomAttributes to GetCustomAttribute change then you will see an error on the SwaggerUi based on a Cast.
As the SwaggerParameter is an attribute that only can be set once per property there is no issue on the change
I have studied if inserting a test in Swashbuckle.AspNetCore.Annotations.Test, but the existing test are hitting this change, so I think there is no need to add it(In fact I have not seen a test using MinimalApi approach)
> AsParameters throwing error on cast when showing the Description with EnableAnnotations

- src/Swashbuckle.AspNetCore.Annotations/AnnotationsRequestBodyFilter.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_For_Mvc_swaggerRequestUri=v1.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_For_WebApi_swaggerRequestUri=v1.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_startupType=Basic.Startup_swaggerRequestUri=v1.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_startupType=CliExample.Startup_swaggerRequestUri=v1.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_startupType=ConfigFromFile.Startup_swaggerRequestUri=v1.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_startupType=CustomUIConfig.Startup_swaggerRequestUri=v1.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_startupType=CustomUIIndex.Startup_swaggerRequestUri=v1.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_startupType=GenericControllers.Startup_swaggerRequestUri=v1.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_startupType=MultipleVersions.Startup_swaggerRequestUri=1.0.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_startupType=MultipleVersions.Startup_swaggerRequestUri=2.0.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_startupType=OAuth2Integration.Startup_swaggerRequestUri=v1.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_startupType=ReDoc.Startup_swaggerRequestUri=v1.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_startupType=TestFirst.Startup_swaggerRequestUri=v1-generated.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.TypesAreRenderedCorrectly.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/Swashbuckle.AspNetCore.IntegrationTests.csproj
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGeneratorVerifyTests/SwaggerGeneratorVerifyTests.GetSwagger_GenerateConsumesSchemas_ForProvidedOpenApiOperationWithSeveralFromForms.verified.txt
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGeneratorVerifyTests/SwaggerGeneratorVerifyTests.cs
- test/WebSites/WebApi/EndPoints/OpenApiEndpoints.cs
- test/WebSites/WebApi/EndPoints/SwaggerAnnotationsEndpoints.cs
- test/WebSites/WebApi/EndPoints/XmlCommentsEndpoints.cs
- test/WebSites/WebApi/Program.cs
- test/WebSites/WebApi/WebApi.csproj
Fixes #2662. Very similar to #2962 PR. When the RequestBody had a SwaggerRequestBody attribute the attribute was not applying and it provoked an exception
> Fix RequestBodyFilterAnnotation and MultipleFromForm for MinimalApi 

- README.md
Add a badge to the README that links to all the help-wanted issues.
> Add help wanted badge

- src/Swashbuckle.AspNetCore.ReDoc/ReDocMiddleware.cs
- src/Swashbuckle.AspNetCore.ReDoc/ReDocOptions.cs
- src/Swashbuckle.AspNetCore.ReDoc/ResourceHelper.cs
- src/Swashbuckle.AspNetCore.ReDoc/Swashbuckle.AspNetCore.ReDoc.csproj
- src/Swashbuckle.AspNetCore.ReDoc/index.css
- src/Swashbuckle.AspNetCore.ReDoc/index.html
- src/Swashbuckle.AspNetCore.ReDoc/index.js
- src/Swashbuckle.AspNetCore.SwaggerUI/ResourceHelper.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptions.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/Swashbuckle.AspNetCore.SwaggerUI.csproj
- src/Swashbuckle.AspNetCore.SwaggerUI/index.html
- src/Swashbuckle.AspNetCore.SwaggerUI/index.js
- test/Swashbuckle.AspNetCore.IntegrationTests/ReDocIntegrationTests.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerUIIntegrationTests.cs
Resolves #2881.
Moved inline javascript to separate files
ReDoc: Moved inline CSS to separate file
SwaggerUi: Reused CSS file from the package
Middleware changes to respond with corresponding files
> Move inline css and js to external files for SwaggerUI and ReDoc

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_For_WebApi_swaggerRequestUri=v1.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.TypesAreRenderedCorrectly.verified.txt
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGeneratorVerifyTests/SwaggerGeneratorVerifyTests.GetSwagger_GenerateConsumesSchemas_ForProvidedOpenApiOperationWithIFormFile.verified.txt
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGeneratorVerifyTests/SwaggerGeneratorVerifyTests.GetSwagger_GenerateConsumesSchemas_ForProvidedOpenApiOperationWithIFormFileCollection.verified.txt
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGeneratorVerifyTests/SwaggerGeneratorVerifyTests.cs
- test/WebSites/WebApi/EndPoints/OpenApiEndpoints.cs
This PR fixes #2625.
The documentation generated from Swashbuckle when the paramater was a FormFile or FormFileCollection was missing the Properties section in the Schema
> Missing Properties section when generating IFomFile/IFormFileCollection

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_For_WebApi_swaggerRequestUri=v1.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.TypesAreRenderedCorrectly.verified.txt
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGeneratorVerifyTests/SwaggerGeneratorVerifyTests.GetSwagger_GenerateConsumesSchemas_ForProvidedOpenApiOperationWithIFormFile.verified.txt
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGeneratorVerifyTests/SwaggerGeneratorVerifyTests.GetSwagger_GenerateConsumesSchemas_ForProvidedOpenApiOperationWithIFormFileCollection.verified.txt
> Missing Encoding and RequiredProperties when IformFile withOpenApi

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_For_WebApi_swaggerRequestUri=v1.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.TypesAreRenderedCorrectly.verified.txt
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGeneratorVerifyTests/SwaggerGeneratorVerifyTests.cs
- test/Swashbuckle.AspNetCore.TestSupport/ApiExplorer/ApiDescriptionFactory.cs
- test/WebSites/WebApi/EndPoints/SwaggerAnnotationsEndpoints.cs
This PR fixes #2733.
It's a continuation of #2532 but with the VerifyTest running over IntegrationTest.
The issue is that the type for MvcWithNullable was coming as string(And its a LogLevel)
And the modelMetadata.ModelType that is coming from SwaggerAnnotationsEndpoints was coming as string.
So.. The best of both worlds
> Use apiParameter.Type when it does not lie

- src/Swashbuckle.AspNetCore.Swagger/SwaggerMiddleware.cs
Use `HttpMethods.IsGet()` instead of a string comparison.
> Use HttpMethods.IsGet()

- src/Swashbuckle.AspNetCore.Newtonsoft/SchemaGenerator/JsonPropertyExtensions.cs
- src/Swashbuckle.AspNetCore.Newtonsoft/SchemaGenerator/NewtonsoftDataContractResolver.cs
- test/Swashbuckle.AspNetCore.Newtonsoft.Test/Fixtures/DataMemberAnnotatedType.cs
- test/Swashbuckle.AspNetCore.Newtonsoft.Test/Fixtures/JsonObjectAnnotatedType.cs
- test/Swashbuckle.AspNetCore.Newtonsoft.Test/Fixtures/JsonPropertyAnnotatedType.cs
- test/Swashbuckle.AspNetCore.Newtonsoft.Test/Fixtures/JsonRequiredAnnotatedType.cs
- test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
Resolves #2383
- Add non-regression tests to ensure [DataMember(IsRequired)] do not bypass existing [JsonObject], [JsonProperty] or [JsonRequired] attributes.
- Add tests for [DataMember(IsRequired)] and [DataMember(name)]
- Update NewtonsoftDataContractResolver to directly leverage jsonProperty.Required, instead of using the IsRequiredSpecifed extension method
> Support [DataMember] IsRequired in NewtonsoftDataContractResolver

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/MemberInfoExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.TestSupport/Fixtures/TypeWithNullableContext.cs
Fixes #3022 
Fixes both issues described in the bug, namely:
1) Correctly describing `Dictionary<string, int>?` as having the `int` value being NON nullable in `additionalProperties`
2) Support `IDictionary<,>` and `IReadOnlyDictionary<,>` in addition to `Dictionary<,>` so that the behavior is consistent across interface vs concrete
> Fixes nullability problems with dictionaries

- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsRequestBodyFilter.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/FakeControllerWithXmlComments.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsRequestBodyFilterTests.cs
- Fix form parameters not being annotated with XML documentation.
- Refactor filter to use modern C# and be slightly more efficient.
- Remove commented-out code in test controller.
Resolves #3018.
> Fix missing form parameter XML documentation

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/MemberInfoExtensions.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.TestSupport/Fixtures/TypeWithNullableContext.cs
A follow-up of #3022 (issue) and #3023 (PR).
The #3023 PR broke the behavior for many of our `IReadOnlyDictionary<string, string>` (and similar) members.
The reason is that the logic for reading and interpreting `NullableAttribute` and `NullableContextAttribute` flags is too simplified and is incorrect for several cases. It just happens to pass the current test cases because of the layout of the test type and its members.
For example, it ignores the optimization of the flags array into a single byte if they are all the same value. An optimized `Dictionary<string, string>` has a single `[1]` flag, not two or three flags as the current logic expects.
It also does a lot of assumptions related to reference vs value types. An IDictionary itself can be a value type, as can the key, both of …
> Use NullabilityInfoContext to determine dictionary value nullability

- global.json
- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/MemberInfoExtensions.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.TestSupport/Fixtures/TypeWithNullableContext.cs
Fixes #3040
We have to address the case when model type is nested-within-nested. In this case for nullable context analysis we have to traverse the whole declaring type chain
In issue example NullableContextAttribute is on the outer class
Sharplab example: https://sharplab.io/#v2:D4AQTAjAsAUCDMACciDCiDetE+UkALIgLIAUAlJtrgL6x0ywKIBOApgMYD2LAJogC0uXCKSEiAdOLCIAMmwBubADYQANMggAGOYpUQAygBcWASwB2AcwAKLLgAdysLDFx5WnHv2ljhYKcJI8krKYBog2rohYMZmVrYOTq64Lm5uzOzcfIKBpBE6wSrwsRY2do4A3NQ4DDRAA
> Fix nested types nullable context check

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/MemberInfoExtensions.cs
Add-on to https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/3043 (should be no conflict)
Very similar to my previous PR: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/3041
In his PR, @VladimirTyrin surgically fixes a specific problem for all platforms. I suggest we use the new and fancy NET6+ toys when available, to avoid custom nullable logic completely in the future. I tested it with the same added test as in @VladimirTyrin's original PR.
> Use NullabilityInfoContext to determine if member is nullable

- src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenOptionsExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XPathNavigatorExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsDocumentFilter.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsDocumentHelper.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsExampleHelper.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsOperationFilter.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsParameterFilter.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsRequestBodyFilter.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsSchemaFilter.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs
Fixes #2164
This is a rebase and enhancement of #2443  (thanks to @stevendarby, added you as co-author).
This significantly improves the performance of the XML comment filters. The original fix #2443 created a dictionary of the members to avoid iterating the whole XPath for every single item.
I made some further improvements by replacing all usages of `Select` and `SelectSingleNode` with `SelectChildren` (added some helper extensions for this). This completely avoids XPath expressions and [the documentation](https://learn.microsoft.com/en-us/dotnet/standard/data/xml/select-xml-data-using-xpathnavigator#optimized-selection-methods) even mentions `SelectChildren` being faster.
I made the new constructors internal for now (which is also why I changed `ParameterFilter` to …
> Improve IncludeXmlComments performance (2)

- .gitignore
- Directory.Packages.props
- Swashbuckle.AspNetCore.sln
- benchmark.ps1
- perf/Swashbuckle.AspNetCore.Benchmarks/Program.cs
- perf/Swashbuckle.AspNetCore.Benchmarks/Swashbuckle.AspNetCore.Benchmarks.csproj
- perf/Swashbuckle.AspNetCore.Benchmarks/XmlCommentsBenchmark.cs
Add project for running benchmarks.
Adapted from https://github.com/mus65/Swashbuckle.AspNetCore/commit/65bfd9745ca2cb757326b79cf3ef88959239af4d.
See #3044.
> Add benchmarks project

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.TestSupport/Fixtures/Enums.cs
When enum used as a key for the dictionary contains no values defined, the dictionary schema becomes an object with no properties. In such case SchemaGenerator should build schema based on dictionary key and value type rather than known key values (which are unknown in fact).
SchemaGenerator was modified to use "special case where the set of key values is known" only if the collection of known dictionary keys is not empty.
> SwaggerGen - Improved handling of dictionaries with enum key

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_For_WebApi_swaggerRequestUri=v1.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.TypesAreRenderedCorrectly.verified.txt
- test/WebSites/Basic/Controllers/FilesController.cs
- test/WebSites/WebApi/EndPoints/OpenApiEndpoints.cs
Fixes #3084
Tested with IntegrationTest
> Fixing breaking change when applying filters for WithOpenApi extension

- src/Swashbuckle.AspNetCore/Swashbuckle.AspNetCore.nuspec
This PR fixes #2706 by passing the defined `Swashbuckle.AspNetCore.props` file to the `buildMultiTargeting` directory, which is used for outer builds (Multi targeting). 
The props file defines that the `OpenApiGenerateDocumentsOnBuild` property is false by default if it's not set. However, this was not set for multi targeting projects. So the document was generated during the build.
> fix: Pass props to multi targeting

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_For_WebApi_swaggerRequestUri=v1.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.TypesAreRenderedCorrectly.verified.txt
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/FakeController.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGeneratorVerifyTests/SwaggerGeneratorVerifyTests.GetSwagger_Works_As_Expected_When_TypeIsEnum_AndModelMetadataTypeIsString.verified.txt
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGeneratorVerifyTests/SwaggerGeneratorVerifyTests.cs
- test/WebSites/WebApi/EndPoints/OpenApiEndpoints.cs
Fixes #3105
It's not a full rollback of #2980..  But almost, now it takes into account the Enum if the apiParameter.Type is Enum
> Types with TryParse must be set with type string

- src/Swashbuckle.AspNetCore.ReDoc/PublicAPI/PublicAPI.Unshipped.txt
- src/Swashbuckle.AspNetCore.ReDoc/ReDocMiddleware.cs
- src/Swashbuckle.AspNetCore.ReDoc/ReDocOptions.cs
- src/Swashbuckle.AspNetCore.ReDoc/ReDocOptionsJsonContext.cs
- src/Swashbuckle.AspNetCore.ReDoc/Swashbuckle.AspNetCore.ReDoc.csproj
- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/ReDocIntegrationTests.cs
- test/WebSites/WebApi.Aot/Program.cs
- test/WebSites/WebApi.Aot/WebApi.Aot.csproj
- Add support for using the ReDoc middleware in native AoT applications.
- Add missing test coverage for ReDoc extensions.
- Fix some code analysis suggestions.
- Fix native AoT test app exception on start-up (see #2951).
> Add native AoT support for ReDoc

- src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/ConfigureSwaggerGeneratorOptions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenOptions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenOptionsExtensions.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/ConfigureSwaggerGeneratorOptionsTests.cs
Given that the public API allows to register a filter in this form without any specific validation on not assigning the Type property:
```csharp
genOptions.OperationFilterDescriptors.Add(new FilterDescriptor
{
// Type = typeof(TdpHeaderParameter),
FilterInstance = new TdpHeaderParameter(IRequestContext.UserIdKey, "The user ID."),
});
```
in which case, opening the swagger UI returns a `NullReferenceException` (in developer error page) with no reference to user source code.
Looking into the library source code, I found out that the "proper" way to do the registration is:
```csharp
genOptions.AddOperationFilterInstance(
new TdpHeaderParameter(IRequestContext.TenantIdKey, "The tenant ID."));
```
but I just felt that the first option should also be available with minimal behavior changes, …
> Refactor filter descriptor type checks in SwaggerGen

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsRequestBodyFilter.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_Basic_DotNet_6.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_Basic_DotNet_8.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_For_WebApi_swaggerRequestUri=v1.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.TypesAreRenderedCorrectly.verified.txt
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/FakeController.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGeneratorVerifyTests/SwaggerGeneratorVerifyTests.GetSwagger_Works_As_Expected_When_FromFormObject.verified.txt
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGeneratorVerifyTests/SwaggerGeneratorVerifyTests.GetSwagger_Works_As_Expected_When_FromFormObject_AndString.verified.txt
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGeneratorVerifyTests/SwaggerGeneratorVerifyTests.cs
- test/WebSites/Basic/Controllers/FromFormParamsController.cs
- test/WebSites/WebApi/EndPoints/OpenApiEndpoints.cs
- test/WebSites/WebApi/EndPoints/SwaggerAnnotationsEndpoints.cs
Fixes #3126.
Also I have found that there was an error for WithOpenApi for FromFormParameters that are enums
> Fix FromForm without WithOpenApi schemas

- src/Swashbuckle.AspNetCore.ReDoc/package-lock.json
- src/Swashbuckle.AspNetCore.SwaggerUI/package-lock.json
- Delete `node_modules` folder and `package-lock.json` file
- `npm install`
Before `npm ci`:
```
added 270 packages, and audited 271 packages in 4s
92 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
node_modules folder size: 76.6 MB
```
After:
```
added 228 packages, and audited 229 packages in 4s
92 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
node_modules folder size: 69.8 MB
```
> Recreate package lock files

- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
Check operations count where we are declaring few `apiDescriptions`.
Use `nameof`
> More asserts for `SwaggerGeneratorTests`

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_Basic_DotNet_8.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_startupType=Basic.Startup_swaggerRequestUri=v1.verified.txt
Fixes #3163.
I tested the last execution with dotnet6(I did not look at dotnet 8 Verification file), and also aspnetcore must have change something in type, for dotnet 8 is string, and for dotnet 6 it was the enum. The ModelMetadata.ModelType hasn't changed and is the one that is being used for generating the schema
> Fix issue with FromForm and enums for Controllers

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/MemberInfoExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/MemberInfoExtensionsTests.cs
- Do not throw if we cannot determine the nullability of a dictionary. It's better to potentially be wrong, rather than be unable to generate a document at all.
- Clean-up some code analysis suggestions.
Resolves #3070.
Resolves #2793 (as it's the last linked issue).
> Avoid exception checking nullability

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/ApiParameterDescriptionExtensions.cs
Fix `NotSupportedException` being thrown with .NET 9
when accessing `ModelMetadata.ElementType` in a native AoT application due to `Microsoft.AspNetCore.Mvc.ApiExplorer.IsEnhancedModelMetadataSupported` being disabled.
Found while investigating #3153.
> Fix NotSupportedException in AoT test project

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
> Add space between duplicated actions in SwaggerGeneratorException

- src/Swashbuckle.AspNetCore/Swashbuckle.AspNetCore.nuspec
Add missing package readme for Swashbuckle.AspNetCore to [avoid warning on publish](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/actions/runs/12008985504/job/33473214694#step:4:16).
```console
Run dotnet nuget push "*.nupkg" --api-key *** --skip-duplicate --source https://api.nuget.org/v3/index.json
Pushing Swashbuckle.AspNetCore.7.1.0.nupkg to 'https://www.nuget.org/api/v2/package'...
PUT https://www.nuget.org/api/v2/package/
warn : Readme missing. Go to https://aka.ms/nuget-include-readme learn How to include a readme file within the package.
Created https://www.nuget.org/api/v2/package/ 258ms
Your package was pushed.
```
The solution used for all the other packages doesn't work for this meta-package as it uses a `.nuspec` file so the MSBuild properties don't apply.
> Add package README

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
This change fixes #3187
The if indicates this was the intended method call to use.
> Allow no match to be found to avoid throwing an exception

- Directory.Build.props
- src/Swashbuckle.AspNetCore.ReDoc/PublicAPI/PublicAPI.Shipped.txt
- src/Swashbuckle.AspNetCore.ReDoc/PublicAPI/PublicAPI.Unshipped.txt
- src/Swashbuckle.AspNetCore.SwaggerGen/PublicAPI/PublicAPI.Shipped.txt
- src/Swashbuckle.AspNetCore.SwaggerGen/PublicAPI/PublicAPI.Unshipped.txt
- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/OpenApiAnyFactory.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/PublicAPI/PublicAPI.Shipped.txt
- src/Swashbuckle.AspNetCore.SwaggerUI/PublicAPI/PublicAPI.Unshipped.txt
- Add overload to `OpenApiAnyFactory.CreateFromJson()` that supports passing in a `JsonSerializerOptions` as a workaround for #3217 (see https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/3217#issuecomment-2585784829).
- Use concrete types as suggested by analyzers.
- Move unshipped APIs to shipped.
- Bump version to 7.3.0.
Tested it unblocks #3217 manually.
> Add CreateFromJson options overload

- test/Swashbuckle.AspNetCore.Annotations.Test/Swashbuckle.AspNetCore.Annotations.Test.csproj
- test/Swashbuckle.AspNetCore.ApiTesting.Test/Swashbuckle.AspNetCore.ApiTesting.Test.csproj
- test/Swashbuckle.AspNetCore.Cli.Test/Swashbuckle.AspNetCore.Cli.Test.csproj
- test/Swashbuckle.AspNetCore.IntegrationTests/Swashbuckle.AspNetCore.IntegrationTests.csproj
- test/Swashbuckle.AspNetCore.Newtonsoft.Test/Swashbuckle.AspNetCore.Newtonsoft.Test.csproj
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/Swashbuckle.AspNetCore.SwaggerGen.Test.csproj
- test/Swashbuckle.AspNetCore.TestSupport/Swashbuckle.AspNetCore.TestSupport.csproj
- test/WebSites/Basic/Basic.csproj
- test/WebSites/CliExample/CliExample.csproj
- test/WebSites/CliExampleWithFactory/CliExampleWithFactory.csproj
- test/WebSites/ConfigFromFile/ConfigFromFile.csproj
- test/WebSites/CustomDocumentSerializer/CustomDocumentSerializer.csproj
- test/WebSites/CustomUIConfig/CustomUIConfig.csproj
- test/WebSites/CustomUIIndex/CustomUIIndex.csproj
- test/WebSites/GenericControllers/GenericControllers.csproj
- test/WebSites/MinimalApp/MinimalApp.csproj
- test/WebSites/MinimalAppWithHostedServices/MinimalAppWithHostedServices.csproj
- test/WebSites/MultipleVersions/MultipleVersions.csproj
- test/WebSites/NswagClientExample/NswagClientExample.csproj
- test/WebSites/OAuth2Integration/OAuth2Integration.csproj
- test/WebSites/ReDoc/ReDoc.csproj
- test/WebSites/TestFirst.IntegrationTests/TestFirst.IntegrationTests.csproj
- test/WebSites/TestFirst/TestFirst.csproj
- test/WebSites/TopLevelSwaggerDoc/TopLevelSwaggerDoc.csproj
Speed up CI and avoid warnings in test projects for unsupported TFMs by not compiling test projects for `net6.0`.
Relates to #3087.
> Stop testing with .NET 6

- test/WebSites/OAuth2Integration/AuthServer/Config.cs
- test/WebSites/OAuth2Integration/AuthServer/Controllers/AccountController.cs
- test/WebSites/OAuth2Integration/AuthServer/Controllers/ConsentController.cs
- test/WebSites/OAuth2Integration/OAuth2Integration.csproj
- test/WebSites/OAuth2Integration/ResourceServer/Controllers/ProductsController.cs
- test/WebSites/OAuth2Integration/Startup.cs
Fixes https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/3008
This PR replaces **IdentityServer4** with **Duende.IdentityServer**.
- **Replaced** `IdentityServer4` with `Duende.IdentityServer` in project dependencies.
- **Updated** the OAuth2Integration code to be compatible with Duende.IdentityServer.
- **Verified** that all existing integration tests are passing.
> Replace IdentityServer4 with Duende.IdentityServer (#3008)

- test/WebSites/OAuth2Integration/OAuth2Integration.csproj
- Fix typo from #3184 for .NET 9
- Update `Duende.IdentityServer` versions
> Fix #3184 - fix JWT version for .NET 9

- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsTextHelper.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_DotNet6_startupType=Basic.Startup_swaggerRequestUri=v1.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_startupType=Basic.Startup_swaggerRequestUri=v1.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsTextHelperTests.cs
- test/WebSites/Basic/Controllers/CrudActionsController.cs
Fixes #3009
Swagger.ui (or Redoc, I'm not sure) are displaying `\r\n   ` as `<pre>` tag.
PR changes making sure that <para> text is **trimmed** and all line breaks are ignored
> Humanize multiline para tag

- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsTextHelper.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_DotNet6_startupType=Basic.Startup_swaggerRequestUri=v1.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_startupType=Basic.Startup_swaggerRequestUri=v1.verified.txt
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsTextHelperTests.cs
- test/WebSites/Basic/Controllers/CrudActionsController.cs
Resolves #3069
for some reason swagger ui `<pre><code>` is cutting first line from code block
```
<code>this content is cutted
{
"Id": 1
}
</code>
```
here's how `GetAll` looks like
> Humanize multi line code tag

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs
- test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
Fix JsonSerializerDataContractResolver so that it handles square arrays correctly
Fixes #3244
> Fix JsonSerializerDataContractResolver so that it handles square arrays correctly

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_DotNet6_startupType=Basic.Startup_swaggerRequestUri=v1.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_startupType=Basic.Startup_swaggerRequestUri=v1.verified.txt
- test/WebSites/Basic/Controllers/FromQueryParamsController.cs
> Use DeepObject parameter style for dictionary

- src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/ConfigureSwaggerGeneratorOptions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenOptionsExtensions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/PublicAPI/PublicAPI.Shipped.txt
- src/Swashbuckle.AspNetCore.SwaggerGen/PublicAPI/PublicAPI.Unshipped.txt
- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGeneratorOptions.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsDocumentFilter.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsOperationFilter.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsParameterFilter.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsRequestBodyFilter.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsSchemaFilter.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsTextHelper.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/ConfigureSwaggerGeneratorOptionsTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsTextHelperTests.cs
Fixes #2947 
Before version [6.6.2,](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/milestone/21?closed=1) OpenAPI file generation was identical for Linux and Windows, which allowed to correctly process files from different OS (including comparing them on CI), after the version, the carets in the text began to differ. 
{
“name": ‘SomeController’,
“description": “Some description.\r\n\n\<br>\r\n\Some Parameter (para tag)\r\n\”
}
{
“name": ‘SomeController’,
“description": “Some description.\r\n[\r\n]|[\n]\r\n\Some Parameter (para tag)\r\n\”
}
That is, instead of <br> being identical when generated on different OS, different strings started to be generated.
The pool requester replaces the generation based on the EOL of the operating system with the EOL generation previously …
> Optional EOL for XmlComments (#2947)

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
> Fix for ApiDescriptionProvider throws NRE

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
Fixes #3271 
The correct parameter name was generated in the `GenerateParameterAndContext` method, but was not used further.
Added assignment of a new parameter name to the `GenerateOpenApiOperationFromMetadataAsync` method.
Added a unit test.
> Fix DescribeAllParametersInCamelCase usage in GenerateOpenApiOperationFromMetadataAsync

- Directory.Build.targets
- Attempt to fix write conflicts when adding the coverage to the `GITHUB_STEP_SUMMARY`.
- Add the target framework to the coverage report summaries.
This should hopefully fix some of the test flakiness.
> More reliable coverage

- .github/bump-version.ps1
- .github/update-baselines.ps1
- .github/workflows/bump-version.yml
- Swashbuckle.AspNetCore.sln
- src/Swashbuckle.AspNetCore.Annotations/PublicAPI/net6.0/PublicAPI.Shipped.txt
- src/Swashbuckle.AspNetCore.Swagger/PublicAPI/PublicAPI.Shipped.txt
- src/Swashbuckle.AspNetCore.Swagger/PublicAPI/net6.0/PublicAPI.Shipped.txt
- src/Swashbuckle.AspNetCore.SwaggerGen/PublicAPI/net6.0/PublicAPI.Shipped.txt
- src/Swashbuckle.AspNetCore.SwaggerGen/PublicAPI/net6.0/PublicAPI.Unshipped.txt
- Move script to bump the version from inline PowerShell to its own script.
- Copy [script from Polly](https://github.com/App-vNext/Polly/blob/1b7defac50fa00395c3e70e303ec111d4370fabe/eng/update-baselines.ps1) to update Public API baselines.
- Fix incorrectly sorted Public API document.
- Remove obsolete Public API baselines for `net6.0`.
> Improve release automation

- Directory.Build.props
- src/Swashbuckle.AspNetCore.Cli/Program.cs
- src/Swashbuckle.AspNetCore.ReDoc/PublicAPI/PublicAPI.Unshipped.txt
- src/Swashbuckle.AspNetCore.ReDoc/ReDocMiddleware.cs
- src/Swashbuckle.AspNetCore.ReDoc/ReDocOptions.cs
- src/Swashbuckle.AspNetCore.ReDoc/ResourceHelper.cs
- src/Swashbuckle.AspNetCore.ReDoc/Swashbuckle.AspNetCore.ReDoc.csproj
- src/Swashbuckle.AspNetCore.SwaggerUI/PublicAPI/PublicAPI.Unshipped.txt
- src/Swashbuckle.AspNetCore.SwaggerUI/ResourceHelper.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptions.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/Swashbuckle.AspNetCore.SwaggerUI.csproj
- test/Swashbuckle.AspNetCore.IntegrationTests/ReDocIntegrationTests.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerUIIntegrationTests.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/TestSite.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/TestSiteAutofaq.cs
- Embed the versions of redoc and swagger-ui-dist into their respective assemblies as `[AssemblyMetdata]` attributes.
- Remove redundant `GetTypeInfo()` calls.
- Add cache headers to ReDoc and SwaggerUI static files.
Resolves #3336.
> Add cache headers for ReDoc and SwaggerUI

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
This Pull Request should hopefully address an issue where Arrays/Lists of Nullable types where not getting correctly marked as Nullable in the generated swagger.
Resolves #3284
In GenerateSchema -> GenerateSchemaForType I added a check to see if the Array underlying type was nullable. If so, it would mark the corresponding section in the schema (in this case items) with nullable = true.
> Update to fix Lists/Arrays of nullables not getting marked as nullable

- .github/workflows/build.yml
- Directory.Build.targets
- Emit an annotation containing the NuGet package versions when publishing.
- Stop installing the .NET 6 SDK.
> Emit annotation for packages

- src/Swashbuckle.AspNetCore.Newtonsoft/SchemaGenerator/NewtonsoftDataContractResolver.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/snapshots/VerifyTests.SwaggerEndpoint_ReturnsValidSwaggerJson_startupType=Basic.Startup_swaggerRequestUri=v1.DotNet8_0.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/snapshots/VerifyTests.SwaggerEndpoint_ReturnsValidSwaggerJson_startupType=Basic.Startup_swaggerRequestUri=v1.DotNet9_0.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/snapshots/VerifyTests.Swagger_IsValidJson_No_Startup_entryPointType=MvcWithNullable.Program_swaggerRequestUri=v1.DotNet8_0.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/snapshots/VerifyTests.Swagger_IsValidJson_No_Startup_entryPointType=MvcWithNullable.Program_swaggerRequestUri=v1.DotNet9_0.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/snapshots/VerifyTests.Swagger_IsValidJson_No_Startup_entryPointType=WebApi.Program_swaggerRequestUri=v1.DotNet8_0.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/snapshots/VerifyTests.Swagger_IsValidJson_No_Startup_entryPointType=WebApi.Program_swaggerRequestUri=v1.DotNet9_0.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/snapshots/VerifyTests.TypesAreRenderedCorrectly.DotNet8_0.verified.txt
- test/Swashbuckle.AspNetCore.IntegrationTests/snapshots/VerifyTests.TypesAreRenderedCorrectly.DotNet9_0.verified.txt
- test/Swashbuckle.AspNetCore.Newtonsoft.Test/Fixtures/JsonPropertyAnnotatedType.cs
- test/Swashbuckle.AspNetCore.Newtonsoft.Test/Fixtures/JsonRequiredAnnotatedType.cs
- test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
- test/Swashbuckle.AspNetCore.TestSupport/Fixtures/TypeWithNullableProperties.cs
- test/Swashbuckle.AspNetCore.TestSupport/Fixtures/TypeWithValidationAttributes.cs
- test/Swashbuckle.AspNetCore.TestSupport/Fixtures/TypeWithValidationAttributesViaMetadataType.cs
- test/WebSites/MvcWithNullable/Program.cs
Fixes https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/3225
This makes changes to the data contract resolvers so that the nullability of enums comes through with the type information.
From there we can ensure that we can set nullable to true and append null as a possible value.
As the values are different there are two different schemas that get built, one which contains the null value, and one that doesn't.
This does mean however that other sections of code now also need to handle nullable types.
Anywhere that does checks if a type is an enum.
Checking for properties that are nullable but have either `Required`, `JsonRequired` or `JsonProperty` with required set.
Checking for required parameters.
> fix schema for nullable enums

- docs/configure-and-customize-annotations.md
- docs/configure-and-customize-cli.md
- docs/configure-and-customize-redoc.md
- docs/configure-and-customize-swagger.md
- docs/configure-and-customize-swaggergen.md
- docs/configure-and-customize-swaggerui.md
- #3365
- #3405 
- Update broken links
- Use [github's markdown alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) syntax for Note sections
- Replace lambda functions' parameter names to more meaningful
- Split those code blocks that contains code fragments for multiple files
- Add syntax highlight for missing code blocks
- Make the code blocks copy-paste ready
- Annotations: [Preview](https://github.com/peter-csala/Swashbuckle.AspNetCore/blob/3365-improve-formatting-of-the-documentation/docs/configure-and-customize-annotations.md)
- CLI: [Preview](https://github.com/peter-csala/Swashbuckle.AspNetCore/blob/3365-improve-formatting-of-the-documentation/docs/configure-and-customize- …
> [Docs] Improve the formatting of documentation files

- .editorconfig
- .gitattributes
Fix Git and EditorConfig having conflicting line-ending settings and standardise on CRLF (as that was the oldest setting committed to Git).
> Fix conflicting settings

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/OpenApiSchemaExtensions.cs
Fix for https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/3283#discussion_r2106322231: do not read/write fractional numbers in the current culture, which depends on OS-level settings, potentially resulting in unparsable JSON.
According to https://json-schema.org/understanding-json-schema/reference/numeric#number, exponents are allowed, which is why I combined the flags:
```c#
[Flags]
public enum NumberStyles
{
Number = AllowThousands | AllowDecimalPoint | AllowTrailingSign | Integer,
Float = AllowExponent | AllowDecimalPoint | Integer
}
```
> Fix culture-insensitive handling of numbers in RangeAttribute

- Directory.Build.props
Disable static web assets as it can cause file-write conflicts in parallel builds.
> Disable Static Web Assets

- exclusion.dic
- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
- Fix various typos in code found by Visual Studio.
- Fix link to documentation broken by https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/3405.
> Typo fixes

- src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/OpenApiAnyFactory.cs
- src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsExampleHelper.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsExampleHelperTests.cs
> Avoid ArgumentNullException being thrown generating examples

- src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/OpenApiSchemaExtensions.cs
- test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/OpenApiSchemaExtensionsTests.cs
- Use invariant culture when values are `double`.
- Use `decimal.TryParse()` not `Convert.ToDecimal()` so that invalid values are just ignored like they were before.
- Remove duplicate test case.
> Fix RangeAttribute behaviour

- src/Shared/EmbeddedResourceProvider.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/ReDocIntegrationTests.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerUIIntegrationTests.cs
- Fix incorrect length value being stored when embedded resources are not served compressed.
- Extend integration tests to verify that the stream is the same length as the `Content-Length` header.
Fixes #3486 and #3487.
> Fix incorrect Content-Length for swagger-ui and Redoc static assets

- src/Shared/EmbeddedResourceProvider.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/ReDocIntegrationTests.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerUIIntegrationTests.cs
Fix incorrect `ETag` for compressed files by resetting the compressed stream to the beginning before computing the SHA256 hash.
See https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/3486#issuecomment-3049325068.
> Fix incorrect ETag values

- src/Shared/EmbeddedResourceProvider.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/ReDocIntegrationTests.cs
Fix `Accept-Encoding` parsing when there are multiple values or the value includes a quality.
See https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/3486#issuecomment-3049325068.
> Fix `Accept-Encoding` parsing

- src/Shared/EmbeddedResourceProvider.cs
- src/Swashbuckle.AspNetCore.ReDoc/ReDocMiddleware.cs
- src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs
- test/Swashbuckle.AspNetCore.IntegrationTests/ReDocIntegrationTests.cs
- Do not respond with gzip if the quality of an `Accept-Encoding` value is zero. See https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/3492#discussion_r2193530519.
- Add a custom header that returns the Redoc/swagger-ui version to resolved uncovered code.
> Check Accept-Encoding quality

- Directory.Packages.props
Update to the stable release of Microsoft.OpenApi 2.0.0.
> Update Microsoft.OpenApi to 2.0.0

- Directory.Packages.props
- src/Swashbuckle.AspNetCore.ApiTesting.Xunit/Swashbuckle.AspNetCore.ApiTesting.Xunit.csproj
- src/Swashbuckle.AspNetCore.ApiTesting/Swashbuckle.AspNetCore.ApiTesting.csproj
- test/Swashbuckle.AspNetCore.IntegrationTests/Swashbuckle.AspNetCore.IntegrationTests.csproj
- test/WebSites/MvcWithNullable/MvcWithNullable.csproj
- test/WebSites/OAuth2Integration/OAuth2Integration.csproj
- test/WebSites/WebApi/WebApi.csproj
- Bump xunit from 2.4.1 to 2.6.6 to resolve https://github.com/domaindrivendev/Swashbuckle.AspNetCore/security/dependabot/25 and https://github.com/domaindrivendev/Swashbuckle.AspNetCore/security/dependabot/26.
- Bump Microsoft.AspNetCore.Mvc.Testing to resolve https://github.com/domaindrivendev/Swashbuckle.AspNetCore/security/dependabot/27 and https://github.com/domaindrivendev/Swashbuckle.AspNetCore/security/dependabot/28.
- Bump test dependencies to latest versions for .NET 8.0.18 and 9.0.7.
> Update NuGet dependencies

- src/Swashbuckle.AspNetCore.Cli/Program.cs
- test/WebSites/CliExample/Program.cs
- test/WebSites/ConfigFromFile/Program.cs
- test/WebSites/ReDoc/Program.cs
- test/WebSites/TestFirst/Program.cs
Remove long-deprecated `WebHost` usage and instead use `Host`.
Flushed out by trying to use `WebApplicationFactory<T>` for Redoc with #3516.
> Remove WebHost usage

- .github/workflows/actions-lint.yml
Fix permissions missed from #3528.
> Fix permissions

- Directory.Packages.props
- test/WebSites/OAuth2Integration/OAuth2Integration.csproj
Update various NuGet dependencies to their latest versions.
> Update NuGet packages
