domaindrivendev/Swashbuckle.AspNetCore

global.json
src/Swashbuckle.Swagger/Application/SwaggerDocsMIddleware.cs
src/Swashbuckle.Swagger/Application/SwaggerPathHelper.cs
src/Swashbuckle.Swagger/Application/SwaggerServiceCollectionExtensions.cs
src/Swashbuckle.Swagger/Swagger/XmlComments/ApplyXmlActionComments.cs
src/Swashbuckle.Swagger/project.json
src/Swashbuckle.SwaggerUi/Application/RedirectMiddleware.cs
src/Swashbuckle.SwaggerUi/Application/SwaggerUiMIddleware.cs
src/Swashbuckle.SwaggerUi/project.json
test/Swashbuckle.Test/Fixtures/ApiDescriptions/FakeApiDescriptionGroupCollectionProvider.cs
test/Swashbuckle.Test/project.json
test/WebSites/BasicApi/Startup.cs
test/WebSites/BasicApi/project.json
test/WebSites/SecureApi/Startup.cs
test/WebSites/SecureApi/project.json
test/WebSites/VersionedApi/Startup.cs
test/WebSites/VersionedApi/project.json

Updated to beta8 which should close #25 now that beta8 is released.
I have not pushed project.json.lock files because I'm not sure it they should be commited.

Updated to beta8

---

README.md

Name change from AspNet vNext to ASP.NET Core

Naming change to ASP.NET Core in readme.md

---

README.md

The Docs pointed to the wrong app.Use  method

---

src/Swashbuckle.SwaggerGen/Annotations/XmlCommentsModelFilter.cs

Fix null reference in XmlCommentsModelFilter

---

src/Swashbuckle.SwaggerGen/Generator/SwaggerGenerator.cs

I added these using the github editor just as a suggestion so it's completely untested ;)

Description for common status codes

---

src/Swashbuckle.SwaggerGen/Generator/SwaggerGenerator.cs
test/Swashbuckle.SwaggerGen.Test/Generator/SwaggerGeneratorTests.cs
test/Swashbuckle.SwaggerGen.Test/TestFixtures/Fakes/FakeActions.cs

Fixed https://github.com/domaindrivendev/Ahoy/issues/182 and https://github.com/domaindrivendev/Ahoy/issues/81
Replaces https://github.com/domaindrivendev/Ahoy/pull/95

Fixed form and modelbinding parameters generation

---

.gitignore
Ahoy.sln
README.md
appveyor.yml
build-definition.ps1
build.cmd
build.ps1
src/Swashbuckle.Swagger/project.json
src/Swashbuckle.SwaggerGen/project.json
src/Swashbuckle.SwaggerUi/project.json
src/Swashbuckle/project.json
test/Swashbuckle.SwaggerGen.Test/project.json
test/WebSites/Basic/project.json
test/WebSites/CustomIndexHtml/project.json
test/WebSites/CustomUiConfig/project.json
test/WebSites/MultipleVersions/project.json
test/WebSites/SecuritySchemes/project.json
test/WebSites/VirtualDirectory/project.json

TODO BEFORE MERGING:
- Transfer ownership of myget feed
- Create appveyor.com account
- Update badge in README.md
- https://ci.appveyor.com/project/ACCOUNTNAME/ahoy/settings/badges
- Encrypt and replace MyGet push secret in appveyor.yml
- https://ci.appveyor.com/tools/encrypt
- See TODO note in appveyor.yml

AppVoyer CI build and push preview packages to MyGet

---

appveyor.yml
build-definition.ps1
src/Swashbuckle.SwaggerUi/bower.json

Fix https://github.com/domaindrivendev/Ahoy/issues/216

Install node on appveyor

---

src/Swashbuckle.SwaggerUi/bower.json

Fixed https://github.com/domaindrivendev/Ahoy/issues/229

Updated SwaggerUI to 2.2.8

---

src/Swashbuckle.AspNetCore.SwaggerUi/CustomAssets/IndexConfig.cs

Make sure JSConfig is serialized as expected by Swagger UI

---

src/Swashbuckle.AspNetCore.SwaggerGen/Annotations/XmlCommentsOperationFilter.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/Annotations/XmlCommentsOperationFilterTests.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/TestFixtures/Fakes/FakeActions.cs
test/WebSites/Basic/Controllers/FromQueryParamsController.cs
test/WebSites/Basic/Startup.cs

update XML comments filter to support property params

---

README.md

This was such a small typo, I didn't want to waste your time by asking you to fix it.

Fix tiny readme typo

---

src/Swashbuckle.AspNetCore.Swagger/Application/SwaggerMiddleware.cs

Hello,
This should fix #288 by leaving the response stream open.
What do you think ?

fix #288 : leave response stream open on swagger json endpoint

---

src/Swashbuckle.AspNetCore.Swagger/Swashbuckle.AspNetCore.Swagger.csproj
src/Swashbuckle.AspNetCore.SwaggerGen/Swashbuckle.AspNetCore.SwaggerGen.csproj
src/Swashbuckle.AspNetCore.SwaggerUI/Swashbuckle.AspNetCore.SwaggerUI.csproj
src/Swashbuckle.AspNetCore/Swashbuckle.AspNetCore.csproj
test/Swashbuckle.AspNetCore.IntegrationTests/Swashbuckle.AspNetCore.IntegrationTests.csproj
test/Swashbuckle.AspNetCore.SwaggerGen.Test/Swashbuckle.AspNetCore.SwaggerGen.Test.csproj

Re : https://github.com/dotnet/corefx/issues/19535
Updates transient dependencies on vulnerable packages.
Microsoft.AspNetCore.Mvc.Core/1.0.0
Microsoft.AspNetCore.Mvc.Formatters.Json/1.0.0
Microsoft.AspNetCore.Mvc.ApiExplorer/1.0.0
Microsoft.AspNetCore.Mvc.DataAnnotations/1.0.0
System.Text.Encodings.Web/4.0.0 via Microsoft.AspNetCore.Http.Abstractions/1.0.0
Microsoft.AspNetCore.Mvc.Core/1.0.0 via Microsoft.AspNetCore.Mvc.ApiExplorer/1.0.0
Microsoft.AspNetCore.Mvc.Abstractions/1.0.0 via Microsoft.AspNetCore.Mvc.Core/1.0.0
Microsoft.AspNetCore.Mvc.Core/1.0.0 via Microsoft.AspNetCore.Mvc.DataAnnotations/1.0.0
Microsoft.AspNetCore.Mvc.Core/1.0.0 via Microsoft.AspNetCore.Mvc.Formatters.Json/1.0.0
System.Text.Encodings.Web/4.0.0 via Microsoft.AspNetCore.WebUtilities/1.0.0 …

Bump vulnerable packages

---

README.md

SwaggerSchemaFilter is undocumented. https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/Annotations/SwaggerSchemaFilterAttribute.cs
Ref https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/606#issuecomment-367896732

Update readme to document SwaggerSchemaFilter

---

README.md
src/Swashbuckle.AspNetCore.SwaggerGen/Application/SwaggerGenOptions.cs
src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SwaggerGenerator.cs
src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SwaggerGeneratorSettings.cs
test/WebSites/OAuth2Integration/Startup.cs

Simplifies addition of global security requirements.

Adds AddSecurityRequirementMethod to SwaggerGenOptions

---

src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SchemaRegistry.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/Generator/SchemaRegistryTests.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/Generator/TypeExtensionsTests.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/TestFixtures/Types/AnAnnotatedEnum.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/TestFixtures/Types/AnEnum.cs
test/WebSites/Basic/Controllers/CrudActionsController.cs

Honor EnumMember when describing enums

---

README.md
src/Swashbuckle.AspNetCore.SwaggerGen/Generator/ApiParameterDescriptionExtensions.cs
src/Swashbuckle.AspNetCore.SwaggerGen/Generator/JsonPropertyExtensions.cs
src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SwaggerGenerator.cs
src/Swashbuckle.AspNetCore.SwaggerGen/Generator/TypeExtensions.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/Generator/SchemaRegistryTests.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/Generator/SwaggerGeneratorTests.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/TestFixtures/Fakes/FakeActions.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/TestFixtures/Fakes/FakeApiDescriptionGroupCollectionProvider.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/TestFixtures/Types/ComplexType.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/TestFixtures/Types/DataAnnotatedType.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/TestFixtures/Types/MetadataAnnotatedType.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/TestFixtures/Types/ModelBoundType.cs

Set parameter required based on model binding & data validation behavior

---

README.md
src/Swashbuckle.AspNetCore.SwaggerGen/Annotations/XmlCommentsDocumentFilter.cs
src/Swashbuckle.AspNetCore.SwaggerGen/Application/SwaggerGenOptions.cs
src/Swashbuckle.AspNetCore.SwaggerGen/Generator/IDocumentFilter.cs
src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SwaggerGenerator.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/Annotations/XmlCommentsDocumentFilterTests.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/TestFixtures/Fakes/FakeControllers.cs
test/WebSites/Basic/Controllers/CrudActionsController.cs
test/WebSites/Basic/Startup.cs

Option to use controller XML summaries for tag descriptions

---

README.md

added command how to install a package on CLI
dotnet add package Swashbuckle.AspNetCore

Install package through CLI

---

src/Swashbuckle.AspNetCore.Swagger/Application/SwaggerMiddleware.cs
src/Swashbuckle.AspNetCore.SwaggerGen/Annotations/SwaggerResponseAttributeFilter.cs
src/Swashbuckle.AspNetCore.SwaggerGen/Generator/JsonContractExtensions.cs
src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SchemaExtensions.cs
src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SchemaIdManager.cs
src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SwaggerGenerator.cs

was just browsing the code and notices some minor optimisations using new c# features.
Feel free to close if u prefer the old style :)

Minor tweaks using new c# features

---

README.md
src/Swashbuckle.AspNetCore.SwaggerGen/Annotations/XmlCommentsSchemaFilter.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/Annotations/XmlCommentsSchemaFilterTests.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/TestFixtures/Types/XmlAnnotatedType.cs

Fixes https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/742

Support <examples> xml comments on fields

---

src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptionsExtensions.cs
test/WebSites/CustomUIConfig/Startup.cs
test/WebSites/CustomUIConfig/wwwroot/ext/custom-javascript.js

I re-introduced the InjectJavascript method, and updated the CustomUIConfig example to inject text at the top of the page.

Support for including custom Javascript in default UI (fixes #705)

---

src/Swashbuckle.AspNetCore.ReDoc/ReDocBuilderExtensions.cs
src/Swashbuckle.AspNetCore.ReDoc/ReDocMiddleware.cs
src/Swashbuckle.AspNetCore.Swagger/Application/SwaggerBuilderExtensions.cs
src/Swashbuckle.AspNetCore.Swagger/Application/SwaggerMiddleware.cs
src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIBuilderExtensions.cs
src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs

support DI-based options for middleware components

---

src/Swashbuckle.AspNetCore.Cli/Program.cs

Excape path in cli arguments

---

src/Swashbuckle.AspNetCore.SwaggerUI/Swashbuckle.AspNetCore.SwaggerUI.csproj

Addresses https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/931

Sign SwaggerUI with a strong-name

---

README.md

Thank you @domaindrivendev for updating this package, I have released nuget packages and would like to add this link so that anyone using Azure Functions can now benefit from this work!

Add link to Swashbuckle.AspNetCore.AzureFunctions

---

src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsSchemaFilter.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/Swashbuckle.AspNetCore.SwaggerGen.Test.csproj
test/Swashbuckle.AspNetCore.SwaggerGen.Test/TestFixtures/Types/XmlAnnotatedType.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsSchemaFilterTests.cs

In this PR I've fixed #959: for some types I've added convertation to appropriate OpenApi type.

Example from <example> xml comment use the correct type

---

README.md

Added info in the readme file about how to display operation ids in swagger ui

Added OperationsId example for Swagger UI

---

README.md

Fix spelling mistake of Relative

---

src/Swashbuckle.AspNetCore.SwaggerGen/Application/SwaggerGenOptionsExtensions.cs
src/Swashbuckle.AspNetCore.SwaggerGen/Application/SwaggerGenServiceCollectionExtensions.cs
src/Swashbuckle.AspNetCore.SwaggerGen/Generator/DocumentProvider.cs
src/Swashbuckle.AspNetCore.SwaggerGen/Generator/IDocumentProvider.cs
test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerGenIntegrationTests.cs

- aspnet/AspNetCore#4948
/cc @domaindrivendev 
/fyi @mkartak

Add `IDocumentProvider` service

---

src/Swashbuckle.AspNetCore.ReDoc/ReDocMiddleware.cs
src/Swashbuckle.AspNetCore.ReDoc/Swashbuckle.AspNetCore.ReDoc.csproj
src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs
src/Swashbuckle.AspNetCore.SwaggerUI/Swashbuckle.AspNetCore.SwaggerUI.csproj

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1061

ASP.NET Core 3.0 support ---- StaticFileMiddleware

---

src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGen/PrimitiveSchemaGenerator.cs

added TimeSpan to FactoryMethodMap

---

src/Swashbuckle.AspNetCore.SwaggerUI/index.html

Remove Goolge Fonts

---

README-v5.md
src/Swashbuckle.AspNetCore.ReDoc/package-lock.json
src/Swashbuckle.AspNetCore.ReDoc/package.json
src/Swashbuckle.AspNetCore.SwaggerUI/package-lock.json
src/Swashbuckle.AspNetCore.SwaggerUI/package.json

Update ReDoc and Swagger-UI

---

src/Swashbuckle.AspNetCore.SwaggerGen/Generator/OpenApiAnyFactory.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/Generator/OpenApiAnyFactoryTests.cs

Fix for casting issue in open api any factory #1207

---

README-v5.md
README.md

Update README.md and README-v5.md.

Add "Unchase.Swashbuckle.AspNetCore.Extensions" to Community Packages in README

---

src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/ApiParameterDescriptionExtensions.cs
src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
test/WebSites/Basic/Controllers/DataAnnotationsController.cs

Honor data annotation attributes on parameters

---

src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/TypeExtensions.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGen/SchemaGeneratorTests.cs

Support IAsyncEnumerable if STJ serializer is being used

---

src/Swashbuckle.AspNetCore.SwaggerGen/Application/ConfigureSchemaGeneratorOptions.cs
src/Swashbuckle.AspNetCore.SwaggerGen/Application/SwaggerGenOptionsExtensions.cs
src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGeneratorOptions.cs
test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs

Make allOf behavior (i.e. to extend reference schemas) opt-in

---

src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs

Support custom mappings on open generic types

---

src/Swashbuckle.AspNetCore.Swagger/DependencyInjection/SwaggerBuilderExtensions.cs
src/Swashbuckle.AspNetCore.Swagger/SwaggerEndpointOptions.cs
test/WebSites/Basic/Startup.cs

- closes #1401
- Add endpoint routing support

Add endpoint routing support

---

src/Swashbuckle.AspNetCore.Annotations/AnnotationsSchemaFilter.cs
src/Swashbuckle.AspNetCore.Annotations/SwaggerSchemaAttribute.cs
test/Swashbuckle.AspNetCore.Annotations.Test/AnnotationsSchemaFilterTests.cs
test/Swashbuckle.AspNetCore.Annotations.Test/Fixtures/FakeControllerWithSwaggerAnnotations.cs

Support SwaggerSchemaAttribute on action parameters

---

appveyor.yml
src/Swashbuckle.AspNetCore.Cli/Swashbuckle.AspNetCore.Cli.csproj
test/WebSites/CliExample/CliExample.csproj
test/WebSites/CliExampleWithFactory/CliExampleWithFactory.csproj

Target Cli to netcoreapp2.1 only to address compat issues

---

src/Swashbuckle.AspNetCore.Swagger/SwaggerMiddleware.cs
src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/ConfigureSwaggerGeneratorOptions.cs
src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenOptionsExtensions.cs
src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGeneratorOptions.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
test/WebSites/NetCore21/Startup.cs

Add config method to simplify adding server(s) information

---

Directory.Build.props

GH1650: Enable SourceLink with embedded PDB

---

src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsNodeNameHelper.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/XmlAnnotatedType.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/Swashbuckle.AspNetCore.SwaggerGen.Test.xml
test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsNodeNameHelperTests.cs

#1689 Fix documentation for multiple nested classes

---

src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs
test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs

Generate empty schemas for JsonDocument & JsonElement types

---

src/Swashbuckle.AspNetCore.Cli/Program.cs

Configure default host with simple startup name instead of FullName

---

README.md

I think that the docs don't matched the correct attribute name for frombody

Correct parameter in docs

---

src/Swashbuckle.AspNetCore.Newtonsoft/SchemaGenerator/NewtonsoftDataContractResolver.cs
src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs
src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
test/WebSites/Basic/Controllers/ResponseTypeAnnotationsController.cs

Generate empty schema for typeof(object) + honor ProblemDetailsConverter

---

src/Swashbuckle.AspNetCore.ApiTesting/Swashbuckle.AspNetCore.ApiTesting.csproj
src/Swashbuckle.AspNetCore.Swagger/Swashbuckle.AspNetCore.Swagger.csproj
test/Swashbuckle.AspNetCore.Annotations.Test/Swashbuckle.AspNetCore.Annotations.Test.csproj
test/Swashbuckle.AspNetCore.ApiTesting.Test/Swashbuckle.AspNetCore.ApiTesting.Test.csproj
test/Swashbuckle.AspNetCore.Cli.Test/Swashbuckle.AspNetCore.Cli.Test.csproj
test/Swashbuckle.AspNetCore.IntegrationTests/Swashbuckle.AspNetCore.IntegrationTests.csproj
test/Swashbuckle.AspNetCore.Newtonsoft.Test/Swashbuckle.AspNetCore.Newtonsoft.Test.csproj
test/Swashbuckle.AspNetCore.SwaggerGen.Test/Swashbuckle.AspNetCore.SwaggerGen.Test.csproj
test/WebSites/TestFirst.IntegrationTests/TestFirst.IntegrationTests.csproj

Hi, 
Mostly it relates to [this issue](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1805)

Update Microsoft.OpenApi & XUnit packages

---

src/Swashbuckle.AspNetCore.Swagger/SwaggerMiddleware.cs

Yaml serialization fix

---

src/Swashbuckle.AspNetCore.ReDoc/ReDocMiddleware.cs
src/Swashbuckle.AspNetCore.Swagger/SwaggerMiddleware.cs
src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs
test/Swashbuckle.AspNetCore.IntegrationTests/ReDocIntegrationTests.cs
test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerGenIntegrationTests.cs
test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerUIIntegrationTests.cs
test/Swashbuckle.AspNetCore.IntegrationTests/TestSite.cs
test/WebSites/Basic/Startup.cs
version.props

Addresses
- #1779
- #1807 
- #1814
- #1836

Infer server metadata based on request Scheme, Host and PathBase

---

README.md

Hi,
After reading https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1616 and https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1667, I figured that an example of how to handle Enum keys in a dictionary could be valuable. 
I found just relying on `c.MapType<>()` sucked when it was a complicated TValue (eg. a `Dictionary<TEnum, List<ComplexObject>`); this SchemaFilter approach lets the swagger generator build the actual values' schemas.
Feel free to close if you disagree! At least those issues will benefit from having this example linked in them.

Add DictionaryTKeyEnumTValueSchemaFilter example to docs

---

src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SystemTextJsonBehavior.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/SystemTextJsonBehaviorTests.cs
test/Swashbuckle.AspNetCore.TestSupport/Fixtures/BaseInterface.cs

#1886 Include properties defined in base interface in SchemaGenerator

---

src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SystemTextJsonBehavior.cs
src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/TypeExtensions.cs
test/Swashbuckle.AspNetCore.Newtonsoft.Test/NewtonsoftSerializerTesting.cs
test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/JsonSerializerTesting.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/SystemTextJsonSchemaGeneratorTests.cs
test/Swashbuckle.AspNetCore.TestSupport/Fixtures/KeyedCollectionOfComplexType.cs

Set UniqueItems if enumerable type is constructed from KeyedCollection

---

Directory.Build.props
src/Swashbuckle.AspNetCore.Annotations/Swashbuckle.AspNetCore.Annotations.csproj
src/Swashbuckle.AspNetCore.ApiTesting.Xunit/Swashbuckle.AspNetCore.ApiTesting.Xunit.csproj
src/Swashbuckle.AspNetCore.ApiTesting/Swashbuckle.AspNetCore.ApiTesting.csproj
src/Swashbuckle.AspNetCore.Newtonsoft/Swashbuckle.AspNetCore.Newtonsoft.csproj
src/Swashbuckle.AspNetCore.ReDoc/Swashbuckle.AspNetCore.ReDoc.csproj
src/Swashbuckle.AspNetCore.Swagger/Swashbuckle.AspNetCore.Swagger.csproj
src/Swashbuckle.AspNetCore.SwaggerGen/Swashbuckle.AspNetCore.SwaggerGen.csproj
src/Swashbuckle.AspNetCore.SwaggerUI/Swashbuckle.AspNetCore.SwaggerUI.csproj
src/Swashbuckle.AspNetCore/Swashbuckle.AspNetCore.csproj
src/Swashbuckle.AspNetCore/Swashbuckle.AspNetCore.nuspec

The CLI package does not have a license. This would take care of it globally.

Add PackageLicenseExpression to apply to all packages

---

src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/OpenApiSchemaExtensions.cs
src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/OpenApiAnyFactory.cs
src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsParameterFilter.cs
src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsSchemaFilter.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/FakeConstructedControllerWithXmlComments.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/FakeControllerWithXmlComments.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/XmlAnnotatedType.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/Swashbuckle.AspNetCore.SwaggerGen.Test.xml
test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsSchemaFilterTests.cs

Fixes #1647
Fixes #1649
Fixes #1892

Simplify syntax for XML Comments examples & support object examples

---

src/Swashbuckle.AspNetCore.Annotations/AnnotationsSchemaFilter.cs
src/Swashbuckle.AspNetCore.Annotations/SwaggerSchemaAttribute.cs
test/Swashbuckle.AspNetCore.Annotations.Test/AnnotationsSchemaFilterTests.cs
test/Swashbuckle.AspNetCore.Annotations.Test/Fixtures/SwaggerAnnotatedType.cs

Support setting Nullable via SwaggerSchemaAttribute

---

README.md

Removed extra bracket

---

README.md
src/Directory.Build.props
src/Swashbuckle.AspNetCore.ReDoc/ReDocBuilderExtensions.cs
src/Swashbuckle.AspNetCore.ReDoc/ReDocMiddleware.cs
src/Swashbuckle.AspNetCore.Swagger/SwaggerMiddleware.cs
src/Swashbuckle.AspNetCore.Swagger/SwaggerOptions.cs
src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIBuilderExtensions.cs
src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs
test/Swashbuckle.AspNetCore.IntegrationTests/ReDocIntegrationTests.cs
test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerIntegrationTests.cs
test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerUIIntegrationTests.cs
test/WebSites/Basic/Startup.cs

Revert back to page-relative URLs for servers, redirects, config etc.

---

src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs

This PR fixes a "AND"/"OR" logic problem that could cause a property to be added as required multiple times.

Fixed missing parenthesis that could cause a property to be added as required multiple times.

---

src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/OpenApiAnyFactory.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/OpenApiAnyFactoryTests.cs

JSON string with bool value conversion issue

---

src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsParameterFilter.cs
src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsRequestBodyFilter.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsRequestBodyFilterTests.cs

Support requestBody examples via XML comments

---

src/Swashbuckle.AspNetCore.SwaggerUI/package-lock.json
src/Swashbuckle.AspNetCore.SwaggerUI/package.json

Update swagger-ui-dist to 3.52.0

---

src/Swashbuckle.AspNetCore.Annotations/AnnotationsOperationFilter.cs
src/Swashbuckle.AspNetCore.Annotations/SwaggerResponseAttribute.cs
test/Swashbuckle.AspNetCore.Annotations.Test/AnnotationsOperationFilterTests.cs
test/Swashbuckle.AspNetCore.Annotations.Test/Fixtures/FakeControllerWithSwaggerAnnotations.cs

Fixes https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1691

Add SwaggerResponseAttribute.ContentTypes property

---

README.md

It's currently not easy to find out how to handle file downloads.
You wrote a comment in this issue https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1034#issuecomment-466983437 and I think it should be part of the documentation.

File download documentation

---

src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptions.cs
src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptionsExtensions.cs
test/WebSites/CustomUIConfig/Startup.cs

https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#authorization

Added persistAuthorization parameter

---

README.md

In response to https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1629#issuecomment-915384316
Sorry if the whitespace doesn't look correct, I was using GitHub's inline editor :-/

Add XML comment list example to Readme

---

src/Swashbuckle.AspNetCore.SwaggerUI/package-lock.json
src/Swashbuckle.AspNetCore.SwaggerUI/package.json

This will fix a security issue reported here: https://github.com/swagger-api/swagger-ui/issues/7446

Update swagger-ui-dist to 3.52.1

---

README.md

Add docs for exposing the generated Swagger as JSON endpoint(s)  with endpoint-based routing

Add docs for endpoint-based routing.

---

src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/TypeWithParameterizedConstructor.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/TypeWithParameterlessAndJsonAnnotatedConstructor.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/TypeWithParameterlessAndParameterizedConstructor.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
test/WebSites/MinimalApp/MinimalApp.csproj

Honor correct STJ behavior for immutable types

---

src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs

Use StringComparer.Ordinal for sorting schemas

---

src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs

Dedup enum values after serialization instead of before

---

src/Swashbuckle.AspNetCore.SwaggerUI/package-lock.json
src/Swashbuckle.AspNetCore.SwaggerUI/package.json

* add copy to clipboard to operation summary
* responsive ui display
* render external docs links and descriptions

Upgrade swagger-ui to 4.14.0

---

src/Swashbuckle.AspNetCore.Newtonsoft/SchemaGenerator/NewtonsoftDataContractResolver.cs
src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs

Set DateOnly as string type with date format in schema

---

src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs

Fixes #2528

---

src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsSchemaFilter.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/XmlAnnotatedRecord.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsSchemaFilterTests.cs

Minimal fix for most common case of C#9 constructor.
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1920

C# 9 Record - Read example/summary from positional record

---

src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/MemberInfoExtensions.cs
src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
test/Swashbuckle.AspNetCore.TestSupport/ApiExplorer/ApiDescriptionFactory.cs

* merge some `Where`  and `FirstOrDefault`
* Merge multiple `Where`s into a single `Where`

reduce some linq allocation

---

.github/dependabot.yml
src/Swashbuckle.AspNetCore.ReDoc/package-lock.json
src/Swashbuckle.AspNetCore.ReDoc/package.json

Update redoc to the latest 2.1.3 release and enable dependabot updates.

Bump redoc to 2.1.3

---

.editorconfig

Sort system usings first, rather than strict alphabetical.
See https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2768#issuecomment-2053936433.

Sort system usings first

---

test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerIntegrationTests.cs

@martincostello  I think this will contribute to #2836

Fix flaky tests by locking on the statup type

---

.github/workflows/stale.yml

Fix stale permissions

---

src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/OpenApiSchemaExtensions.cs
test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
test/Swashbuckle.AspNetCore.TestSupport/Fixtures/TypeWithValidationAttributes.cs
test/Swashbuckle.AspNetCore.TestSupport/Fixtures/TypeWithValidationAttributesViaMetadataType.cs

Add support for the `[Length]`attribute.

---

README.md

docs: fix example code formatting

---

src/Swashbuckle.AspNetCore.Newtonsoft/SchemaGenerator/NewtonsoftDataContractResolver.cs
test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
test/Swashbuckle.AspNetCore.Newtonsoft.Test/Swashbuckle.AspNetCore.Newtonsoft.Test.csproj

In the PR #2610 there was missing the Newtonsoft serializer.

Apply SwaggerIgnore on Newtonsoft

---

test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerIntegrationTests.cs
test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_startupType=Basic.Startup_swaggerRequestUri=v1.verified.txt
test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_startupType=CustomDocumentSerializer.Startup_swaggerRequestUri=v1.verified.txt
test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_startupType=NSwagClientExample.Startup_swaggerRequestUri=v1.verified.txt
test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.cs
test/Swashbuckle.AspNetCore.IntegrationTests/Swashbuckle.AspNetCore.IntegrationTests.csproj

Test `NSwagClientExample` in `SwaggerIntegrationTests`. Test `Basic`, `CustomDocumentSerializer` and `NSwagClientExample` in Verify tests.

Test more WebAPI examples

---

Directory.Build.props

Fix symbol packages not being created.
Resolves #3165.

Create snupkg files

---

README.md

Fixes #1014
As proposed in the issue I specifically mentioned that other tags (remarks, para) are not supported.
Also did a little cleanup within 4th paragraph

adjust readme for #1014 issue

---

README.md

Make the supported ASP.NET Core versions more precise.

Update version table

---

.github/workflows/build.yml
Directory.Build.props
Directory.Packages.props
global.json
src/Swashbuckle.AspNetCore.Annotations/AnnotationsDocumentFilter.cs
src/Swashbuckle.AspNetCore.Annotations/AnnotationsOperationFilter.cs
src/Swashbuckle.AspNetCore.ApiTesting/ApiTestRunnerBase.cs
src/Swashbuckle.AspNetCore.ApiTesting/JsonValidation/JsonNumberValidator.cs
src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/OpenApiSchemaExtensions.cs
src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsDocumentFilter.cs
test/Swashbuckle.AspNetCore.ApiTesting.Test/JsonValidatorTests.cs
test/Swashbuckle.AspNetCore.IntegrationTests/DocumentProviderTests.cs
test/Swashbuckle.AspNetCore.IntegrationTests/OpenApiDocumentLoader.cs
test/Swashbuckle.AspNetCore.IntegrationTests/Swashbuckle.AspNetCore.IntegrationTests.csproj
test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
test/Swashbuckle.AspNetCore.SwaggerGen.Test/VerifyTests.cs
test/WebSites/MvcWithNullable/MvcWithNullable.csproj
test/WebSites/OAuth2Integration/OAuth2Integration.csproj
test/WebSites/TestFirst.IntegrationTests/CreateUserTests.cs
test/WebSites/WebApi/WebApi.csproj

Update to preview 3 of ASP.NET Core 10.

Update to ASP.NET Core 10 preview 3

---

.github/workflows/build.yml

Avoid workflow failures until #3368 is resolved.

Disable publishing to MyGet

---

.github/workflows/build.yml
.gitignore
Directory.Build.targets
Directory.Packages.props
build.ps1

Use Codecov's test analytics feature.

Add test analytics

---

src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs

- Remove unused parameter from change in #3377.
- Simplify duplicated condition.

Remove unused parameter

---

.github/workflows/build.yml
Directory.Build.props
Directory.Build.targets
test/Swashbuckle.AspNetCore.IntegrationTests/snapshots/VerifyTests.SwaggerEndpoint_ReturnsValidSwaggerJson_startupType=TestFirst.Startup_swaggerRequestUri=v1-generated.DotNet8_0.verified.txt
test/Swashbuckle.AspNetCore.IntegrationTests/snapshots/VerifyTests.SwaggerEndpoint_ReturnsValidSwaggerJson_startupType=TestFirst.Startup_swaggerRequestUri=v1-generated.DotNet9_0.verified.txt
test/WebSites/CliExample/CliExample.csproj
test/WebSites/OAuth2Integration/OAuth2Integration.csproj
test/WebSites/TestFirst.IntegrationTests/CreateProductTests.cs
test/WebSites/TestFirst.IntegrationTests/CreateUserTests.cs
test/WebSites/TestFirst.IntegrationTests/GetProductsTests.cs
test/WebSites/TestFirst/wwwroot/swagger/v1-generated/openapi.json
test/WebSites/TestFirst/wwwroot/swagger/v1-imported/openapi.json

Cherry-pick changes from #3283 to reduce the diff.

.NET 10 preparation

---

.github/workflows/build.yml

Re-enable publishing to MyGet.
Resolves #3368.

Re-enable MyGet publishing

---

Directory.Packages.props

Bump Verify.XunitV3 to the latest version.

Bump Verify.XunitV3

---

test/WebSites/Basic/Controllers/CrudActionsController.cs

Test Results are supported in Net10

---

.github/workflows/actions-lint.yml

Bump zizmor

---

Directory.Packages.props
test/Swashbuckle.AspNetCore.IntegrationTests/Swashbuckle.AspNetCore.IntegrationTests.csproj
test/WebSites/MvcWithNullable/MvcWithNullable.csproj
test/WebSites/OAuth2Integration/OAuth2Integration.csproj
test/WebSites/WebApi/WebApi.csproj

Update various dependencies, including Microsoft.OpenApi, to their latest minor/patch versions.

Update NuGet dependencies

---

.github/workflows/dependency-review.yml

Add license for Microsoft.OpenApi v2.

Update allowed licences
